### PR TITLE
Adds Occitan

### PR DESCRIPTION
**Pull request by Mejans**
I cannot find the .po file for Occitan in the latest release =/
I suspect this is why :(

### CODE REVIEW

**Comment by cschramm** [comment]
`oc` is already included at the bottom of that file.
It only exists in master, though, and has not been included in any release yet. It will be part of 2.2, which is finally around the corner (https://github.com/blueman-project/blueman/milestone/4).

**Comment by Mejans** [comment]
How comes it's not in the release of October the 27th whereas Weblate did the update in September?
It's frustrating :( I thought I didn't miss the train.

**Comment by cschramm** [comment]
There are separate translations on Weblate for the master and the 2-1-stable branch. 2.1.x releases are based on the 2-1-stable branch that doesn't have oc. master will be 2.2 and there hasn't been a release yet (sorry for being slow there).

**Comment by Mejans** [comment]
I cross my fingers for version 2.2 then :)

**Pull request closed without merging**
