### PR TITLE
Implement udhcpc support

### LINKED ISSUE #237: Could blueman be made to work with udhcpc
Just a suggestion, but could blueman be made to work with udhcpc (busybox) for network connections?

### PR DESCRIPTION
**Pull request by cschramm**
Refactor blueman.main.DhcpClient to avoid duplication. Adding udhcpc support is actually done by just adding it to the COMMANDS array.

Closes #237

### CODE REVIEW

**Comment by juanitotc** [comment]
Sorry, but I'm a little confused - is this functionality (udhcpc as opposed to udhcpd) added yet?

**Comment by cschramm** [comment]
Yes, this PR (#244) brings udhcpc support for the DhcpClient plugin from branch udhcpc.

**Comment by juanitotc** [comment]
OK, I re-cloned and recompiled the udhcpc branch, but it fails with this:

blueman-applet

notify (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:235)
<Device object at 0x7f5df663bf50 (blueman+main+Device+Device at 0x1e45c80)> <blueman.services.NetworkAccessPoint.NetworkAccessPoint object at 0x7f5df66516d0> 00001116-0000-1000-8000-00805f9b34fb 
_________
initialize (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:140)
rebuilding menu 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:21)
caching initial properties 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:65)
deleting device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:87)
invalidating device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
err (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DhcpClient.py:49)
org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python2.7/site-packages/blueman/main/DbusService.py", line 31, in wrapper
    return method(*args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/mechanism/Network.py", line 28, in DhcpClient
    dh.connect("error-occurred", dh_error, ok, err)
TypeError: connect() takes exactly 1 argument (5 given) 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:21)
caching initial properties

----------

blueman-manager

_________
success (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:105)
success (dbus.String(u'bnep0'),) 
_________
unset_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:91)
op: regenerating instance <ManagerDeviceMenu object at 0x7f30189cf3c0 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x20eeb20)> 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:165)
j-frankish iPhone 
_________
unset_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:91)
op: regenerating instance <ManagerDeviceMenu object at 0x7f30189edf50 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x20eeda0)> 
/usr/local/lib/python2.7/site-packages/gi/overrides/__init__.py:92: Warning: Source ID 3061 was not found when attempting to remove it
  return fn(*args, **kwargs)

**Comment by cschramm** [comment]
Sorry, I made a mistake there. Should be fixed.

**Comment by juanitotc** [comment]
I still can't get it to work - I can see it's trying:

`$ ps aux | grep udhcpc
 2786 root     /sbin/udhcpc -b -i eth0 -x hostname boxdell -p /var/run/udhcpc.eth0.pid
 3299 root     udhcpc -b -i wlan0 -x hostname boxdell -p /var/run/udhcpc.wlan0.pid
26928 root     /sbin/udhcpc -t 20 -n -i bnep0`

..but no connection is made before I get the connection failed pop-up.

blueman-applet

notify (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:235)
<Device object at 0x7ffb71b92f50 (blueman+main+Device+Device at 0x2571860)> <blueman.services.NetworkAccessPoint.NetworkAccessPoint object at 0x7ffb71b4b610> 00001116-0000-1000-8000-00805f9b34fb 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:65)
deleting device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:87)
invalidating device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
initialize (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:140)
rebuilding menu 
_________
err (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DhcpClient.py:49)
org.freedesktop.DBus.Python.int: int: 1

----------

blueman-manager

success (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:105)
success (dbus.String(u'bnep0'),) 
_________
unset_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:91)
op: regenerating instance <ManagerDeviceMenu object at 0x7fb25755f0a0 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x2290a90)> 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:165)
j-frankish iPhone 
_________
unset_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:91)
op: regenerating instance <ManagerDeviceMenu object at 0x7fb25755f410 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x2290d10)> 
/usr/local/lib/python2.7/site-packages/gi/overrides/__init__.py:92: Warning: Source ID 1959 was not found when attempting to remove it
  return fn(*args, **kwargs)
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:165)
j-frankish iPhone

**Comment by cschramm** [comment]
In https://github.com/blueman-project/blueman/pull/238#issuecomment-89967741 you mentioned getting

> Read error: Network is down, reopening socket udhcpc: bind: No such device

So it seems there's something wrong with your connection. Does the service stay connected according to blueman? Can you check the state with `ip link` or similar?

**Comment by juanitotc** [comment]
That was when I compiled the udpcpd branch by mistake instead of the udhcpc branch, the above error is with the udhcpc branch.

**Comment by juanitotc** [comment]
I tried again with the same result, I see from:

` /sbin/udhcpc -t 20 -n -i bnep0`

..that blueman is trying to make the connection, but it seems to fail (silently) and bnep0 disappears as soon as it fails (as per ifconfig). The iPhone does not show the blue "personal hotspot" bar at the top of the screen.

Is there any other trouble-shooting I can do?

**Comment by cschramm** [comment]
You could of course try a different DHCP client, but I don't think your issue is udhcpc related (it works for me like dhclient does).

The question is if it's an issue with DHCP (e.g. the iPhone does not offer an address for some reason) or with the underlying connection. Is bnep0 actually up while blueman tries to get the lease?

If it's up you could use tcpdump to see what's going on on the link.

In any case the debug output of bluetoothd, starting at the point where you connect to the service, could give a clue what's wrong.

**Comment by juanitotc** [comment]
As per bluetoothd, bnep0 is only up for about 4 seconds - is this enough for udhcpc to make the connection?

As per ifconfig, bnep0 is up while the "attempting to connect" pop-up is present, but disappears after.

For troubleshooting purposes would it be possible to have bluetoothd hold the connection open and background udhcpc?

bluetoothd[7660]: profiles/network/connection.c:connection_connect() id 4374
bluetoothd[7660]: profiles/network/connection.c:bnep_conn_cb() 
bluetoothd[7660]:  connected
bluetoothd[7660]: src/service.c:change_state() 0x23171c0: device 54:E4:3A:22:48:E9 profile network-nap state changed: disconnected -> connected (0)
bluetoothd[7660]: src/service.c:change_state() 0x23171c0: device 54:E4:3A:22:48:E9 profile network-nap state changed: connected -> disconnected (0)
bluetoothd[7660]: bnep0 disconnected

$ ifconfig
...
bnep0     Link encap:Ethernet  HWaddr A0:A8:CD:2C:3E:17  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:16 (16.0 B)  TX bytes:425 (425.0 B)

**Comment by cschramm** [comment]
4 seconds?! Hrm... Sounds like the iPhone drops the connection. I'll try to get my hands on one and see if encounter a similar behavior.

**Comment by juanitotc** [comment]
Any news? It'd be great to get udhcpc working :)

**Pull request closed without merging**
