### PR TITLE
Add checking for optional PulseAudio

### PR DESCRIPTION
**Pull request by yars068**
Check for PulseAudio is installed.

### CODE REVIEW

**Comment by cschramm** [comment]
I like the fact that it's runtime optional so it's up to the user to have pa installed or not, so I would definitely ship the support in a binary package (given that pulseaudio is available in the distribution as well). But I guess it makes sense to be able to disable it for users who use the source version or some kind of source package where they can set configuration options.

If no objections are raised, I'll merge it in a couple of days. Thanks for the contribution! :smiley: 

Side note: As I mention in #294 I'm not sure if blueman's pulseaudio integration makes much sense anymore anyway.

**Comment by infirit** [comment]
While I don't see the point as pulse module is a runtime del only and the exception is handled properly, but if this makes folks happy go for it :). I do have a couple of comments.

Just use blueman_PYTHON += pulsefile in Makefile.am and avoid the else part. And have_pulseaudio is not used outside configure.ac so no point calling AC_SUBST on it.

**Comment by yars068** [comment]
@infirit, thanks for criticism, I just started learning autotools, python and C :)

**Comment by cschramm** [comment]
If I see that right, you changed it so that it's disabled by default now. Please change this to enabled.

**Comment by yars068** [comment]
Just changed, and also added checking for libappindicator.

**Comment by cschramm** [comment]
It does not make sense to check for pulseaudio and libappindicator on the build system. The build may include the code or not, but it's the target system that may have the respective package. No need for it on the build system. So especially the warning of it's enabled but not present on the build system, does not make sense.

**Comment by yars068** [comment]
Ok, I will remove the warnings about that.

**Comment by yars068** [comment]
Ok, warnings is removed.

**Comment by cschramm** [comment]
If I get the right, the option to not include those files is now only respected if the respective packages are not available on the build system. That doesn't make sense to me. Just remove the PKG_CHECK_MODULES completely and stay with the AC_ARG_ENABLE to provide an option to skip those files.

**Comment by yars068** [comment]
Oh, sorry, that is my mistake, fixed.

**Comment by cschramm** [comment]
Looks good to me now.

**Comment by yars068** [comment]
Also some small fixes on AC_CONDITIONAL tests.

**Comment by cschramm** [comment]
OK, please squash all those commits and I'll merge it.

**Comment by yars068** [comment]
Done, forced update from my local repository.

**Pull request closed without merging**
