### PR TITLE
BluezAgent: Close Notification when pair in successful

### PR DESCRIPTION
**Pull request by infirit**
According to [1] BlueZ should call the Cancel method on the agent but for
some reason it doesn't. See [2]

[1] https://git.kernel.org/cgit/bluetooth/bluez.git/tree/doc/agent-api.txt
[2] https://github.com/blueman-project/blueman/issues/164

### CODE REVIEW

**Comment by cschramm** [comment]
I think we should also disconnect the signal in the handler, because a) it's a memory leak as every device showing such a dialog creates a blueman.bluez.Device object that never gets destroyed and b) there might be an edge case where we cancel the wrong notification / dialog:

* Pairing is initiated for device A -> a notification is shown and a handler is connected.
* Either pairing for A is not completed or it gets unpaired after successfully pairing it -> now it's still / again unpaired, no notification is shown, and the handler resides.
* Pairing is initiated for device B -> a notification is shown (and a handler is connected).

If you now manage to pair A (outside of blueman, e.g. using bluetoothctl), the first handler that's still in place is triggered and cancels the notification for B.

**Comment by infirit** [comment]
> it's a memory leak as every device showing such a dialog creates a blueman.bluez.Device object that never gets destroyed

Does a connected signal count as a reference? If not then the local reference is gone and garbage collection should kick in. To be safe we can make sure to diconnect, more below.

>there might be an edge case where we cancel the wrong notification / dialog

Would that not be the same if BlueZ called the Cancel method on it's own? iow this looks like a design flaw/bug in the BluezAgent not keeping track of the notification. For example [``self.n``](https://github.com/blueman-project/blueman/blob/master/blueman/main/applet/BluezAgent.py#L187) is not checked at all and blindly replaces it with a new notification, or am I missing something? I am not saying we shouldn't handle this, just saying this commit does not change the logic. I can add a dict like I did in [``blueman-adapters``](https://github.com/blueman-project/blueman/commit/89bb6fb0c3f54a556ce4a9e00f0fcb1957675ad5) which holds all the notifications and signal id's and lookup notifications by device path.

**Comment by cschramm** [comment]
> Does a connected signal count as a reference?

Yes, the glib code holds its own reference, so either all handlers must be disconnected or you can delete the object explicitly (`blueman.bluez.Base.__del__` should disconnect the handlers then).

> Would that not be the same if BlueZ called the Cancel method on it's own?

I don't think so. In my example we would trigger `Cancel` for a pairing process our agent did not even handle (as e.g. another handler was set up in `bluetoothctl`). I would not expect BlueZ to trigger `DisplayPasskey` on one agent (`bluetoothctl`'s) and `Cancel` for the same process on another one (blueman's), however we would do that if we have a PropertyChanged handler for the device.

**Comment by infirit** [comment]
Ok, so in short; 
 1. keep track of devices we initiate pairing.
 2. call ``Cancel`` on only those to close the notification.
 3. clean-up after ourselves.

I'll code this up tonight and update this PR.

**Comment by cschramm** [comment]
I think achieving point 3 also fixes the others. It should be enough to keep the latest return value of `dev.connect_signal` to do a `disconnect_signal` in `Cancel`.

With this patch, `Cancel` should now be called no matter what happens to the pairing process, so we're guaranteed to clean-up and to not falsely running into `Cancel` later on.

**Comment by infirit** [comment]
Updated the PR which now clean up. I did end up storing the signal and the object so we can properly disconnect later. I now also included the case were the user may have entered the wrong pin/passkey and we end up calling the Display* functions more than once for the same device.

However, I did think of another potential corner case. What if the user ends up pairing more devices this way? We probably end up with multiple BluezDevice objects of which we can only properly handle the last one.

**Comment by cschramm** [comment]
I thought about that case as well. I think - but I'm in the dark here - that in case pairing for a device was started the agent should always get `Cancel` before getting `Display*` or whatever for another device. However if BlueZ has the concept of multiple parallel pairing processes, this obviously does not hold. If it's really a problem, a solution would be to also disconnect the signal from the last device when connecting it on another device.

Regarding the current PR: You would not need to store the object as it's the first parameter (`device`) for the signal handler (thus the reference). The patch looks good to me. :+1:

**Comment by infirit** [comment]
Fixed the storing of the device and pushed. Thx

**Pull request merged**
