### PR TITLE
Updating the translators list

### PR DESCRIPTION
**Pull request by wtuemura**

### CODE REVIEW

**Comment by cschramm** [comment]
Looks like Weblate does not maintain that list (it's from Transifex). I guess we need to find a solution to credit the translators but maintaining that list by hand is not it. :sweat_smile: 

My suggestion would be:
* Create a wiki page for Launchpad and Transifex translators
* Remove Transifex translators from PO files
* Link to link to a Weblate page that shows the translators (I only found a manual export, yet, though :thinking:) and the wiki page with Launchpad and Transifex translators in the about dialog
* Remove Launchpad translators from about dialog

**Comment by cschramm** [comment]
...and I have to apologize, @wtuemura. I dumped your changes to the stable compoment as it was not too stable yet. :worried: Could you please re-apply them? They are in the history and Weblate also still remembers and offers the translations that you added for previously untranslated messages. https://hosted.weblate.org/changes/?component=stable&project=blueman&lang=pt_BR&user=wtuemura

**Comment by wtuemura** [comment]
Done.

**Comment by cschramm** [comment]
> Link to link to a Weblate page that shows the translators

I still fail to find some page like that on Hosted Weblate. :thinking:

**Review by infirit — APPROVED** [review]

**Comment by wtuemura** [comment]
> > Link to link to a Weblate page that shows the translators
> 
> I still fail to find some page like that on Hosted Weblate.

There is none that I'm aware of, maybe you can [report the issue](https://github.com/WeblateOrg/weblate) and make a feature request.

**Comment by fitojb** [comment]
> Looks like Weblate does not maintain that list (it's from Transifex). I guess we need to find a solution to credit the translators but maintaining that list by hand is not it. 

Weblate updates it if you enable a setting: https://docs.weblate.org/en/latest/admin/addons.html#contributors-in-comment

**Comment by fitojb** [comment]
@cschramm Please don’t drop the credits for the translators on older platforms, it’d be violating their copyright!!

**Comment by cschramm** [comment]
@fitojb: Thanks for the hint. I enabled that.

In what legislation would removing credits violate copyright? Or do you mean it violates the license granted with their contributions to Launchpad?

**Comment by fitojb** [comment]
That’s what I meant; apologies for being unclear.

**Comment by cschramm** [comment]
@fitojb: I'm seriously confused about the Launchpad translations license and blueman. It seems like the translations we have from there were contributed (~2009) under a BSD license (see https://help.launchpad.net/Translations/LicensingFAQ) that Launchpad required since somewhere 2008 (see https://help.launchpad.net/Translations/LicensingFAQ), however I do not get the implications at all.

The BSD license says:
> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

Such copyright notices and the BSD license never even found their way into blueman. All we have there is a list of translators under the msgid `translator-credits`.

I guess legally the original authors already violated the license when they pulled the translations from Launchpad without putting the BSD license somewhere. It's questionable, though, if Launchpad even provided it in a way that the licensee could "retain". What happened then is that I took over the project, assuming that "the whole thing is licensed under GPL" is correct.

Anyway, back to the topic: Completely independent of legal stuff I definitely want to credit all contributors including translators.

Current state:

1. GitHub contributors are shown on https://github.com/blueman-project/blueman/graphs/contributors and linked to in our about dialog.
2. Lauchpad translators are in msgid `translator-credits` which is shown in our about dialog.
3. Transifex translators are in the source code (.po files) and are static, so we could easily gather a complete list somewhere.
4. Weblate translators are not really documented as such but Weblate adds them as (co-)authors to its git commits, so they should show up as GitHub contributors.
5. I enabled the "Contributors in comment" Weblate plugin and it seems to seamlessly continue Transifex' work, see https://github.com/blueman-project/blueman/pull/1395/files#diff-fedd02520f415fdac7721a3c9b925569R8, however, it does not seem to add previous contributors.

I think it's unfair that 2 is much more prominent (directly visible in the software) than 1 / 4 (linked to in the software) and 3 / 5 (source code only) and would like to have a complete overview over all contributors. Having a complete list in our about dialog sounds over the top, so I'd prefer one or more links but that would downgrade the Launchpad translators.

@wtuemura: Sorry for taking over your PR for this, but you addressed a generic issue here. :grimacing:

**Comment by wtuemura** [comment]
@cschramm No problem.

**Comment by cschramm** [comment]
A first step of streamlining the credits is in #1441.

This PR is obsolete anyway as Weblate added you automatically in the meantime, @wtuemura. :wink:

**Comment by wtuemura** [comment]
Thank you @cschramm

**Pull request closed without merging**
