### PR TITLE
NetConf: Provide DNS again

### PR DESCRIPTION
**Pull request by infirit**
Let's just do this for now and get this fixed quickly for debian 11.

### CODE REVIEW

**Comment by cschramm** [comment]
Why not #1565? 😄

We can't fix anything for Debian 11. It does not get updates like this.

**Comment by cschramm** [comment]
Debian and Ubuntu releases do not get any updates except security patches.

**Comment by infirit** [comment]
kinda sad that it's now broken on debian 11. Is backports still a thing? If so are you planning on having blueman in there instead?

**Comment by cschramm** [comment]
Sure, there is https://backports.debian.org/. I can upload 2.4 there when it's ready.

I stopped caring, to be honest. There are so many systems out there that basically ship a snapshot and never get any updates. Versions with DNS disabled for dnsmasq are in Debian 11, three currently supported Ubuntu releases (two LTS), with a fourth one in two days and three supported Fedora releases, to just name the most important cases.

**Pull request closed without merging**
