### PR TITLE
2 0 stable

### PR DESCRIPTION
**Pull request by 1nf1del**
many problems

### CODE REVIEW

**Comment by 1nf1del** [comment]
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
.circleci/config.yml
.travis.yml
CHANGELOG.md
apps/blueman-adapters
apps/blueman-applet
apps/blueman-assistant
apps/blueman-mechanism
apps/blueman-sendto
blueman/DeviceClass.py
blueman/Functions.py
blueman/bluez/Adapter.py
blueman/bluez/Manager.py
blueman/bluez/obex/Manager.py
blueman/gui/Animation.py
blueman/gui/DeviceList.py
blueman/gui/DeviceSelectorWidget.py
blueman/gui/Dialogs.py
blueman/gui/GenericList.py
blueman/gui/GtkAnimation.py
blueman/gui/Notification.py
blueman/gui/applet/PluginDialog.py
blueman/gui/manager/ManagerDeviceList.py
blueman/gui/manager/ManagerDeviceMenu.py
blueman/gui/manager/ManagerMenu.py
blueman/gui/manager/ManagerToolbar.py
...

**Comment by infirit** [comment]
No idea what you are trying to do but we will never merge master to the stable branche.

**Comment by 1nf1del** [comment]
I posted the issues , fix them then , or let someone else fix them .

On May 25, 2019 4:25 AM, "Sander Sweers" <notifications@github.com> wrote:

Closed #1034 <https://github.com/blueman-project/blueman/pull/1034>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/blueman-project/blueman/pull/1034?email_source=notifications&email_token=AEM74PGFKDC45WJWEFLBSWLPXCIP5A5CNFSM4HPSP6J2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGORUKL5TQ#event-2366947022>,
or mute the thread

**Comment by cschramm** [comment]
@1nf1del not sure what's going on here but if this is plain trolling you have been warned.

**Comment by 1nf1del** [comment]
I've posted all the error information , from my terminal , none of you
seems to understand the problem with blueman ,I'll just remove it .

**Pull request closed without merging**
