### PR TITLE
Rfcomm: Change dbus type signature to an int

### PR DESCRIPTION
**Pull request by infirit**
Fixes: #2489

### CODE REVIEW

**Review by cschramm — APPROVED** [review]
I'm still wondering why this did not come up yet. Are there any specific conditions that cause the error? :thinking:

**Comment by infirit** [comment]
Not sure. I usually don't use serial devices/rfcomm so I probably never noticed. I completely relied on the the type annotation while I should have done at least a quick test.

**Comment by cschramm** [comment]
Oh, I get it. This only became an issue with https://github.com/blueman-project/blueman/commit/5ea654259c36fd51d43a354fd1af4190e402b376, thus the 2.4 release. I expected an issue that we'd have had for much longer, but it's only due to the f-string.

**Comment by infirit** [comment]
Yeah, I assumed the type hint was correct. Maybe we can change the add_method function to require python types. We might then be able to change the annotation and be more specific than `Callable(..., Any)`. So mypy can help us (mostly me lol) spot these issues.

Maybe a TypeVar if we pass a proper type or maybe even simpler NewType of str for each dbus typestring 🤔 

I may experiment with that when I'm done with the for main PR.

**Pull request merged**
