### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/blueman/blueman/) for blueman/blueman.

### CODE REVIEW

**Comment by cschramm** [comment]
Uh, `msgfmt` doesn't like the missing format specifications in `msgstr[0]` and `msgstr[1]` for the messages with `msgid_plural`... :confused:

**Comment by cschramm** [comment]
I created suggestions on Weblate that replace the numerals with format strings. Otherwise we'd have to relax the check.

**Comment by infirit** [comment]
<pre>msgid "%.0f Minute"
msgid_plural "%.0f Minutes"
msgstr[0] "דקה אחת"
msgstr[1] "שתי דקות"
msgstr[2] "%.0f דקות"
msgstr[3] "%.0f דקות"</pre>

I don't know Hebrew but what I got from google translate is that 0 is ``one minute`` and 1 is ``two minutes``, I don't know if this is proper or not. It is similar to English or Dutch, I can write ``one minute`` or ``1 minute``, the former is nicer to read but technically not correct.

You and I do not really have the knowledge to determine what is correct for all these languages so if we need to relax the check so be it 😃.

**Comment by cschramm** [comment]
My suggestions are at https://hosted.weblate.org/translate/blueman/blueman/he/?q=has:suggestion. Hopy anybody checks them. /ping @yarons

I'm not sure if disabling the check would be that easy. autoconf just copies in a Makefile.in.in that uses `$(MSGFMT) -c` and I'm not sure if it's more flexible with the meson module. Not to say that disabling the check has obvious downsides.

**Comment by yarons** [comment]
Hmm I'm guessing that if it'll only be minutes and seconds we can use your suggestion, the problem starts with hours, weeks, months, years, this is why I'm doing it in the first place, and the fact that it sounds more natural to Hebrew speakers.

**Comment by cschramm** [comment]
I played around a bit and it looks like we can avoid the situation by using mapping keys as `msgfmt --check-fomat` does not require all keys to be used in translations.

We have a total of nine usages of `ngettext`, six of them using format strings. The two in [TransferService.py](https://github.com/blueman-project/blueman/blob/5223119257f71cbc493c1d69363826fb76ce599d/blueman/plugins/applet/TransferService.py) and the two in [Sendto.py](https://github.com/blueman-project/blueman/blob/5223119257f71cbc493c1d69363826fb76ce599d/blueman/main/Sendto.py) are those in question here.

We could change `ngettext("%.0f Minute", "%.0f Minutes", round(x)) % x` to `ngettext("%(minutes).0f Minute", "%(minutes).0f Minutes", round(x)) % {"minutes": x}` to make `msgfmt --check-format` pass even if the translations do not have the format string. We could also change that to `ngettext("%(minutes)d Minute", "%(minutes)d Minutes", round(x)) % {"minutes": round(x)}` to unify it with a very similar string in [Adapter.py](https://github.com/blueman-project/blueman/blob/5223119257f71cbc493c1d69363826fb76ce599d/blueman/main/Adapter.py). I'll draft a patch.

**Comment by cschramm** [comment]
See #1306

**Comment by yarons** [comment]
@cschramm so is it OK for me to remove your suggestions?

**Comment by cschramm** [comment]
The messages I added proposals to should actually be gone on Weblate but it seems like something went wrong at https://github.com/blueman-project/blueman/actions/runs/187699492 (the artifact still shows the old messages). The reason the build passes now is that the translations in question are just not used anymore and thus not checked, as it seems.

**Comment by cschramm** [comment]
I have no idea why the pot file did not get updated there. Will merge this and see if the issue sticks.

**Comment by cschramm** [comment]
Same with https://github.com/blueman-project/blueman/actions/runs/188496543. :sob:

**Comment by cschramm** [comment]
For the record: It looks like the new POT update (#1286) never worked. Fixed in #1315.

**Pull request merged**
