### PR TITLE
blueman-manager: Rework bluetooth disabled dialog

### PR DESCRIPTION
**Pull request by infirit**
I want to cleanup all the nested function in `do_activate`, having some is ok but imo this is too much. Putting it out here for quick testing.

### CODE REVIEW

**Comment by infirit** [comment]
lol, just realized a new menu entry was added to handle this and now it's unreachable when bluetooth is off :fearful: . I can just drop the check/dialog completely but how do we prevent users interacting with the list?

**Comment by cschramm** [comment]
It makes sense to me that the dialog shows up on start but not if Bluetooth gets switched off while blueman-manager is open, but we can also consider dropping the dialog completely in favor of the menu entry. Users should be curious enough to find it in the all-empty, non-functional manager window.

**Comment by infirit** [comment]
I'm mostly concerned with users interacting with the list as most actions will result in errors.

**Comment by cschramm** [comment]
Ah, shoot, I keep forgetting that I'm kind of blind there as my internal adapter gets removed when rfkill blocked (i.e. my list is empty then).

Now I'm immediately wondering: Don't you run into the very same "interact with unavailable devices in the list" problem

a) if the adapter gets powered off or rfkill blocked (without getting removed) while blueman-manager is already running and
b) if you have multiple adapters and *some* are powered off or rfkill blocked.

And yes, while I cannot test rfkill and do not have an external adapter at hand, I can e.g. `bluetoothctl power off` while blueman-manager is running and of course run into errors when trying to connect to devices (both in main and 2.3.5) and with #2132 I can even do that from within blueman-manager now (when disabling the `Killswitch` plugin so that it actually only gets powered off and not removed in my case).

My conclusion is: Yes, there definitely are rough edges (that we should care about), but even without #2132 and with the Bluetooth disabled dialog they're nothing new.

**Comment by cschramm** [comment]
Quick draft for hiding connect items: https://github.com/blueman-project/blueman/commit/a751ad1c8062d2b58fba9fb7620ad45567a26f12

Ideally, some items in `DeviceMenuItem.Group.ACTIONS` should also get hidden, but not all.

Also "Send a file" in the toolbar needs to get disabled and I just realized that its search button is always available. :see_no_evil:

**Comment by infirit** [comment]
The simplest option is to clear/not populate when unpowered. Then show a label that states what the state of things are in. Like 

* Bluetooth not running
* adapter Killswitch enabled
* blueman applet not running
* something I missed

With instructions on how to change the state perhaps...

**Comment by cschramm** [comment]
That would be another quick fix, yes, but I do not really like the idea of hiding the devices as you can still interact with them in terms of removing, trusting, unpairing, renaming etc.

**Comment by cschramm** [comment]
#2183 tries to fix the manager for an unpowered adapter. No matter if we go that way or clear the list, I still fancy to just drop the dialog to fix #1119 #1707 #2161. Anything else will keep things inconsistent as the dialog tries to avoid *starting* blueman-manager with disabled Bluetooth but it is very well possible to have it running with an unpowered adapter.

**Pull request closed without merging**
