### PR TITLE
Add battery levels to manager device list

### PR DESCRIPTION
**Pull request by cschramm**
This is a first approach to #947 and along the way eases the problem in #860 as it does no longer show fake signal levels if a battery level is available.

The pixmaps are super temporary. I hope I'll find an easy way to build this dynamically with icon theme icon + bar + color. Otherwise I'm a little lost as I have no clue how the existing pngs got created.

I'm also working on / thinking about an applet plugin that shows a notification with battery level, probably in combination with #1374. One cannot couple it with the Connected property, though, as the Battery interface is not available initially (the ServicesResolved signal should probably work).

### CODE REVIEW

**Comment by infirit** [comment]
I played around with inkscape a bit (to eventually recreate the rssi/tpl/lq pixmaps) and used https://openclipart.org/detail/303646/fully-charged-battery to make below. I have them in all steps. If you are going to use default icons you are at the mercy of icon themes which may be fine but I have seen some broken icon themes 😨 .

**Comment by cschramm** [comment]
Looks nice. :ok_hand:

**Comment by cschramm** [comment]
How shall we proceed with this? I'd wait for #1432 and then rebase this according to the new rendering scheme. Shall we create a common branch here where you can contribute the icons or shall we do two independent PRs with icons and logic?

**Comment by infirit** [comment]
Here are all of them, 10 - 100 zipped. They can be made into png and then we are dealing bytes in size.

[battery.zip](https://github.com/blueman-project/blueman/files/5648061/battery.zip)

**Comment by cschramm** [comment]
Nice. :+1: I added them as PNGs. Shall we add the SVGs to the source as well? Somewhere like `data/icons/pixmaps/sources`?

**Comment by infirit** [comment]
Ignore my previous comment, I forgot how ManagerDeviceList works :eyes: . Using the png's that are there now is good enough. 

And yes, store the svg's somewhere we can find them later. I don't think we should install them, we could later on if we decide to use them in other places.

**Review by infirit — APPROVED** [review]

**Pull request merged**
