### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by m4sk1n**

### CODE REVIEW

**Comment by m4sk1n** [comment]
@infirit

**Comment by infirit** [comment]
Sorry @m4sk1n, while I can merge this translations are managed out of transifex. I have no access to it so I'll have to wait for @cschramm.

**Comment by m4sk1n** [comment]
@infirit, I see that translation files on Transifex aren't maintained...

**Comment by infirit** [comment]
Not really, it up to date for the latest release but not master. What we probably should do is pull the latest changed from transifex into the 2-0-stable branch and then upload a new pot file for the changed and new strings in master.

**Comment by cschramm** [comment]
Should be done. 🙂

**Pull request closed without merging**
