### PR TITLE
Manager: Use Gtk.Switch to toggle bluetooth status

### PR DESCRIPTION
**Pull request by infirit**
Here is what I have so far. Still need to:
* cleanup
* drop menu entry
* perhaps change color of the button

The idea here is that the toggle button is "active" when bluetooth is enabled and showing label and icon what would happen if the button is pressed, disable bluetooth.

image

image

### CODE REVIEW

**Comment by cschramm** [comment]
I think that makes a lot of sense. :ok_hand:

Not sure about the "active" visualization, though. It feels wrong that the button is highlighted (in sense of a primary action) when it allows to turn Bluetooth off while it's not when it allows to turn it on. From that perspective, I'd expect the contrary.  Not sure, but it might make sense to just not highlight any of the states (I see that the state might be less obvious then).

**Comment by infirit** [comment]
Perhaps a Gtk.Switch is more appropriate as it can have proper on/off labels. Let me are how that looks.

**Comment by infirit** [comment]
Here is how I can look with a switch. I didn't add a label as I don't see what that would add, I can so let me know if you want it.
image
image

**Comment by cschramm** [comment]
I think that's perfect!

**Comment by infirit** [comment]
Cool, I'll commit that and push it tonight.

**Comment by infirit** [comment]
Updated with the switch

**Review by cschramm — APPROVED** [review]

**Review by cschramm — APPROVED** [review]

**Pull request merged**
