### PR TITLE
SerialManager: fix-AttributeError on _on_device_property_changed

### LINKED ISSUE #341: SerialManager: AttributeError: 'Device' has no attribute 'Address'
Hi now,
As you noticed, at end of [these log](http://pastebin.com/1Se9GJk7), seen 
```
_________
_on_property_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBase.py:28)
None Connected 0
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/plugins/applet/SerialManager.py", line 59, in _on_device_property_changed
    self.terminate_all_scripts(device.Address)
AttributeError: 'Device' object has no attribute 'Address'
```
That is unrelated to #340, and for that reason, is another issue. Currently, I have no idea on how to fix it :(

### PR DESCRIPTION
**Pull request by yars068**
I think I fixed #341.  No errors logged, but need a couple of time to complete test :) Currently, I able to receive and transfer files between phone and computer.

### CODE REVIEW

**Comment by cschramm** [comment]
Hm, that may be a second issue...

**Comment by yars068** [comment]
Maybe that patch is not right, but is worked on this function. blueman-applet show [that](https://gist.github.com/yars068/0e8950fb2f1c5b8a5b3c).

**Comment by yars068** [comment]
When tried NAP, I see [this](https://gist.github.com/yars068/e8125c262d34531cbf2d).

**Comment by yars068** [comment]
To cpomparsion with #341 see [this](http://pastebin.com/j170H6Mr).

**Comment by cschramm** [comment]
Basically the patch is right, we are working on the wrong device class here. But it's incorrect as `blueman.main.Device.__init__` requires to be given a `blueman.bluez.Device`. As a result I get:
````
__load_plugin (/home/cschramm/src/blueman/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
Exception KeyError: (u'Properties',) in <bound method Device.__del__ of <Device object at 0x7f82e35827d0 (uninitialized at 0x0)>> ignored
Traceback (most recent call last):
  File "/home/cschramm/src/blueman/blueman/plugins/BasePlugin.py", line 54, in _load
    self.on_load(parent)
  File "/home/cschramm/src/blueman/blueman/plugins/applet/SerialManager.py", line 48, in on_load
    self._any_device = Device()
TypeError: __init__() takes exactly 2 arguments (1 given)
_________
__load_plugin (/home/cschramm/src/blueman/blueman/main/PluginManager.py:133)
Failed to load SerialManager
__init__() takes exactly 2 arguments (1 given) 
````

You're output does not contain anything about loading the SerialManager plugin at all, neither a failure nor a success message. I have no idea why...

Anyway, the issue is also addressed (accidentally) in my patch for #341. I'll review the patch when I find the time and see what issues we have with and without it.

**Comment by yars068** [comment]
> I have no idea why...

This plugin just disabled in "Modules..." dialog.

**Comment by yars068** [comment]
Hmm, when I tried to enable Serialmanager, I get:
```
_________
__load_plugin (/usr/lib64/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
Exception KeyError: (u'Properties',) in <bound method Device.__del__ of <Device object at 0x7f457e2324b0 (uninitialized at 0x0)>> ignored
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/plugins/BasePlugin.py", line 54, in _load
    self.on_load(parent)
  File "/usr/lib64/python2.7/site-packages/blueman/plugins/applet/SerialManager.py", line 48, in on_load
    self._any_device = Device()
TypeError: __init__() takes exactly 2 arguments (1 given)
_________
__load_plugin (/usr/lib64/python2.7/site-packages/blueman/main/PluginManager.py:133)
Failed to load SerialManager
__init__() takes exactly 2 arguments (1 given) 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Deleting plugin instance <blueman.plugins.applet.SerialManager.SerialManager object at 0x7f457e233490>
```

**Pull request closed without merging**
