### PR TITLE
Restore blueman.pot

### PR DESCRIPTION
**Pull request by cschramm**
I picked up #1390 without the manual po update and with the check job.

### CODE REVIEW

**Review by infirit — APPROVED** [review]
lgtm

**Comment by cschramm** [comment]
And I immediate ran into a problem: gettext >= 0.20.2 does not extract Icon names from desktop files anymore and the ubuntu thingy is on 0.19.8, so it still does. Depending on your local gettext version it might or might not detect a difference due to that. I think I'll add a diff output to the job so that it's visible why it detects a difference and check if I can get >= 0.20.2 into the job so that it matches recent versions. That still means one needs to have >= 0.20.2 locally when updating the file (or remove the icon names that get added otherwise by hand afterward).

**Comment by infirit** [comment]
Force the 0.20.2 requirement in configure.ac ``AM_GNU_GETTEXT_VERSION([0.20.2])``

**Comment by infirit** [comment]
> Force the 0.20.2 requirement in configure.ac `AM_GNU_GETTEXT_VERSION([0.20.2])`

And it is not in debian so this may not be a good idea :thinking:

**Pull request merged**
