### PR TITLE
DeviceList: cleanups round one

### PR DESCRIPTION
**Pull request by infirit**
First set of cleanups.

### CODE REVIEW

**Comment by cschramm** [comment]
The assumption in 75f2e10 is not true in case of the device-created signal from the Manager object, is it?

**Comment by infirit** [comment]
There are a couple of cases where we call ``device_add_event`` which is the only one that calls ``add_device``.

 * It is a brand new discovered bluetooth device and it will not exist in the list.
 * We switch to another adapter and we clear the old list.
 * We reorder the list and we again first clear the list and then rebuild.

**Comment by cschramm** [comment]
Brand new, sure. :laughing: 

No more objections then. :+1:

**Comment by infirit** [comment]
Thanks, merged :smile:.

**Pull request merged**
