### PR TITLE
KillSwitch: Do not block when there is nothing to read

### LINKED ISSUE #1498: Blueman shows not devices
blueman: 2.1.r423.gd50b8a20 (e.g.: master)
BlueZ: 5.55
Distribution: ArchLinux
Desktop environment: swaywm

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

`blueman-manager` takes a long while to start up, and then shows no devices (not even the ones that are currently connected).

```
$ blueman-manager
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/main/Manager.py", line 130, in on_dbus_name_appeared
    check_bluetooth_status(_("Bluetooth needs to be turned on for the device manager to function"),
  File "/usr/lib/python3.9/site-packages/blueman/Functions.py", line 65, in check_bluetooth_status
    if "PowerManager" not in applet.QueryPlugins():
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gio.py", line 350, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
gi.repository.GLib.Error: g-io-error-quark: Timeout was reached (24)
```

However, bluetooth is running fine -- I'm using both my mouse and headphones via bluetooth without issues.

Here's the output of `blueman-applet`:

```
$ blueman-applet --loglevel debug
blueman-applet 10.47.35 INFO     PluginManager:85 load_plugin: ['AppIndicator', 'StatusIcon', 'DBusService', 'ShowConnected', 'NMDUNSupport', 'TransferService', 'PPPSupport', 'PowerManager', 'ConnectionNotifier', 'Menu', 'DhcpClient', 'StandardItems', 'Battery', 'NMPANSupport', 'Networking', 'NetUsage', 'GameControllerWakelock', 'AuthAgent', 'DisconnectItems', 'DiscvManager', 'AutoConnect', 'ExitItem', 'RecentConns', 'SerialManager', 'KillSwitch']
blueman-applet 10.47.35 ERROR    PluginManager:90 load_plugin: Unable to load plugin module GameControllerWakelock
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/main/PluginManager.py", line 88, in load_plugin
    importlib.import_module(self.module_path.__name__ + f".{plugin}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/blueman/plugins/applet/GameControllerWakelock.py", line 15, in <module>
    raise ImportError('This is not an X11 screen')
ImportError: This is not an X11 screen
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.Menu.Menu'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'>
blueman-applet 10.47.35 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0 {'Address': '64:5D:86:ED:F9:53', 'AddressType': 'public', 'Name': 'victory', 'Alias': 'victory', 'Class': 3932428, 'Powered': True, 'Discoverable': False, 'DiscoverableTimeout': 180, 'Pairable': False, 'PairableTimeout': 0, 'Discovering': False, 'UUIDs': ['00001133-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001105-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '00001104-0000-1000-8000-00805f9b34fb', '00005005-0000-1000-8000-0002ee000001', '00001108-0000-1000-8000-00805f9b34fb', '00001112-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '0000110a-0000-1000-8000-00805f9b34fb', '00001106-0000-1000-8000-00805f9b34fb'], 'Modalias': 'usb:v1D6Bp0246d0537', 'Roles': ['central', 'peripheral']}
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.DBusService.DBusService'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.TransferService.TransferService'>
blueman-applet 10.47.35 WARNING  PluginManager:147 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.PowerManager.PowerManager'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.Battery.Battery'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.ConnectionNotifier.ConnectionNotifier'>
blueman-applet 10.47.35 WARNING  PluginManager:147 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.StandardItems.StandardItems'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.NMPANSupport.NMPANSupport'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.Networking.Networking'>
blueman-applet 10.47.35 INFO     Networking:35 load_nap_settings: Loading NAP settings
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.DisconnectItems.DisconnectItems'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.AutoConnect.AutoConnect'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.RecentConns.RecentConns'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.SerialManager.SerialManager'>
blueman-applet 10.47.35 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'>
Failed to register: Timeout was reached
blueman-applet 10.48.00 INFO     KillSwitch:106 io_event  : killswitch registered 0
blueman-applet 10.48.00 INFO     KillSwitch:122 io_event  : State: True
blueman-applet 10.48.00 INFO     PowerManager:178 update_power_state: off False | foff False | on True | current state True | new state True
blueman-applet 10.48.00 INFO     KillSwitch:87 _on_connman_vanished: net.connman vanished
```

I'm not sure what the initial timeout refers to, but bluez is also running:

image

### PR DESCRIPTION
**Pull request by infirit**
We basically blocked all of blueman-applet, fixes #1498

Why reading from /dev/rfkill is problematic with kernel 5.11 is still a mystery.

### CODE REVIEW

**Comment by cschramm** [comment]
I just found the problem. The event structure changed: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=14486c82612a177cb910980c70ba900827ca0894

According to the commit message it should not be a problem for existing userspace logic as it will ask for 8 bytes and just get 8 of the now actually 9 bytes. What I don't get is: When it asks again, I think it will either block as only 1 byte is available, just read that byte if it's non-blocking but then it tries to process broken data, or (I'm not quite sure if that's how the channel / file works) it might even read the leftover byte plus 7 bytes of a new event and process garbage data with the expected overall size. I am confused... :confused:

**Comment by infirit** [comment]
There is nothing in the glib docs that suggest that is how it works. I'll add some debug lines and try to pinpoint exactly were it blocks.

Also read() is the old API so I will also try out read_chars() or read_to_end().

**Comment by infirit** [comment]
Your idea that we first get 8 and then 1 bytes is spot on. I added some logging and here is what I get. This is with channel.set_flags(GLib.IOFlags.NONBLOCK).

```
blueman-applet 17.30.42 DEBUG    KillSwitch:96 io_event  : 8 b'\x04\x00\x00\x00\x02\x00\x00\x00'
blueman-applet 17.30.42 INFO     KillSwitch:112 io_event  : killswitch registered 4
blueman-applet 17.30.42 INFO     KillSwitch:128 io_event  : State: True
blueman-applet 17.30.42 INFO     PowerManager:178 update_power_state: off False | foff False | on True | current state True | new state True
blueman-applet 17.30.42 DEBUG    KillSwitch:96 io_event  : 1 b'\x00'
blueman-applet 17.30.42 WARNING  KillSwitch:102 io_event  : Bad rfkill event size: 1
```

Without NONBLOCK we indeed properly read the first 8 bytes but on the next event try to read another 8 while there is only 1 to read.

```
blueman-applet 17.34.40 DEBUG    KillSwitch:96 io_event  : 8 b'\x04\x00\x00\x00\x02\x00\x00\x00'
blueman-applet 17.34.40 INFO     KillSwitch:112 io_event  : killswitch registered 4
blueman-applet 17.34.40 INFO     KillSwitch:128 io_event  : State: True
blueman-applet 17.34.40 INFO     PowerManager:178 update_power_state: off False | foff False | on True | current state True | new state True
```

What is most confusing is that we get another event after reading the initial 8 bytes :confused:

**Comment by infirit** [comment]
Pushed a new approach. Always try to read 9 bytes and check how many we got. With non blocking I can ask the IOChannel for as many bytes as I like but it will only ever return how there actually is.

btw, the new api (read_chars etc) is completely broken in pygobject so don't even attempt making it work.

**Comment by cschramm** [comment]
I could image that we might still read the full 8 bytes of an older kernel version plus the first byte of the next event, so that we'll be left with 7 more. Not sure what that might lead up to then or if it's even true.

**Review by cschramm — APPROVED** [review]

**Comment by infirit** [comment]
> I could image that we might still read the full 8 bytes of an older kernel version plus the first byte of the next event, so that we'll be left with 7 more. Not sure what that might lead up to then or if it's even true.

I agree, it is too iffy so I think we should just go back to using os.read. Will push a new commit for this.

**Comment by cschramm** [comment]
I guess that does not change anything, does it? It still reads along the open file handle.

I cannot follow the whole kernel change reasoning at all, to be honest. When I read my /dev/rfkill right now, I get `0000 0000 0200 0000 0200 0000 0100 0000` (kernel 5.10), i.e. add events for a Bluetooth killswitch with identifier 0 and a WLAN killswitch with identifier 2. Even to read both of them, to get to know the existing killswitches, I need to know the size of the structure (I could read all available data and then see if it's a multiple of 8 or a multiple of 9 as long as it's not a multiple of 72 but obviously I'd be better off with just checking the kernel version :facepalm:). To read actual changes, I then have to keep the file open and read data as it gets available, so this file absolutely has to be consumed in a streaming manner and to do that I have to know the event size.

The "old userspace requests 8 bytes and receives 8 bytes" scheme seems to work if I want to read only one add event and nothing else from the file and I don't see how that can be useful. I'm tempted to file a kernel bug but I fear there won't be a proper solution as the change already happend in a stable release.

**Comment by infirit** [comment]
Fortunately using os.read works fine it is reading IOChannel that is broken here. see below with just ``os.read()``.

```
blueman-applet 12.10.14 INFO     KillSwitch:112 io_event  : killswitch changed 0
blueman-applet 12.10.14 INFO     KillSwitch:122 io_event  : State: False
blueman-applet 12.10.14 INFO     PowerManager:178 update_power_state: off True | foff False | on True | current state True | new state False
blueman-applet 12.10.14 INFO     PowerManager:181 update_power_state: Signalling False
blueman-applet 12.10.14 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0 {'Class': 0, 'Powered': False, 'Discovering': False}
blueman-applet 12.10.14 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Class 0
blueman-applet 12.10.14 INFO     PowerManager:178 update_power_state: off True | foff False | on False | current state False | new state False
blueman-applet 12.10.14 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Powered False
blueman-applet 12.10.14 INFO     DiscvManager:109 on_adapter_property_changed: Stop
blueman-applet 12.10.14 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Discovering False
blueman-applet 12.10.23 INFO     KillSwitch:112 io_event  : killswitch changed 0
blueman-applet 12.10.23 INFO     KillSwitch:122 io_event  : State: True
blueman-applet 12.10.23 INFO     PowerManager:178 update_power_state: off True | foff False | on True | current state False | new state False
blueman-applet 12.10.26 INFO     KillSwitch:112 io_event  : killswitch changed 0
blueman-applet 12.10.26 INFO     KillSwitch:122 io_event  : State: False
blueman-applet 12.10.26 INFO     PowerManager:178 update_power_state: off True | foff False | on False | current state False | new state False
blueman-applet 12.10.28 INFO     KillSwitch:112 io_event  : killswitch changed 0
blueman-applet 12.10.28 INFO     KillSwitch:122 io_event  : State: True
blueman-applet 12.10.28 INFO     PowerManager:178 update_power_state: off True | foff False | on True | current state False | new state False
```

**Comment by infirit** [comment]
I think the only reason read() kinda works is because of the static binding [1]. 

Currently there is no way, that I see, for us to properly read exactly 8 bytes from a IOChannel. Everything I tried, read_chars(), read_line(), read_to_end() all block indefinitely.

I learned my lesson, do not replace working code (it was my suggestion to read from the IOChannel) with low level GLib apis as they are either broken, work completely differently then C or are just not available.

https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/gimodule.c#L1923

**Comment by cschramm** [comment]
I absolutely do not get why an `os.read` for 8 bytes skips the ninth byte, but it seems to work. :shrug: At least I just read only 7 bytes from kernel 5.10 and the next read was aligned to the next event. As you said, `IOChannel.read` does not work as the rest gets returned on the next read.

Still, I'm not sure about the assumptions of the Kernel change. If you read events one by one, it seems to work due to whatever magic, but at least [Documentation/rfkill.txt](https://www.kernel.org/doc/Documentation/rfkill.txt) does not mandate to do so, so I'd assume reading all available data and then splitting it up in chunks of the expected event size would be perfectly fine but now broken with 5.11.

**Review by cschramm — APPROVED** [review]

**Pull request merged**
