### PR TITLE
fix broken schema

### PR DESCRIPTION
**Pull request by leigh123linux**

### CODE REVIEW

**Comment by infirit** [comment]
These are not spelling mistakes. These are relocatable schemas and may have more than one set of settings under the schema path. For example one set of gsmsetting for each phone.

The way they are now is intentional and unless you have actual errors these should stay as they are.

**Comment by cschramm** [comment]
In what way is it broken, @leigh123linux?

**Comment by leigh123linux** [comment]
I thought the empty schemas  displayed in dconf-editor were broken because they have no keys.

**Comment by infirit** [comment]
Yeah, relocatable schemas can be confusing :wink:

**Pull request closed without merging**
