### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [blueman/2.4](https://hosted.weblate.org/projects/blueman/2-4/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by infirit** [comment]
@cschramm I saw the alert from weblate. I think iy means this PR is getting too big. If we merge this would it fix the alert?

I also have no issue pulling the changes manually in a commit if that's needed.

**Review by infirit — APPROVED** [review]

**Comment by infirit** [comment]
I see it has conflicts now 😞 . I'll see if I can fix this later today.

**Comment by cschramm** [comment]
Not sure what's wrong with the new component. In other cases, e.g. #2310, weblate squashes into a single commit which works much better. I don't get why that's not the case for 2.4.

**Comment by infirit** [comment]
I'll check weblate if there is something different compared to main

**Comment by infirit** [comment]
The only difference was the age of changes to the commits which I set to the same as main (168). I'll merge the new PR I pushed from weblate and hopefully it now squashes them from now on :pray: .

**Comment by infirit** [comment]
Looks like I made things worse. After diner I'll do what weblate is suggesting.

**Comment by infirit** [comment]
Ugh, I fixed the conflicts but we still have multiple commits for 2.4. Two new PR are open.

**Comment by cschramm** [comment]
I found it. Sqashing is an addon and the new component did not have any addons installed. I installed them project-wide now.

**Pull request closed without merging**
