### PR TITLE
many PEP8 fixes

### PR DESCRIPTION
**Pull request by infirit**
This is currently already in the fixes PR but that got too large so split these off to a new PR. No functional changes.

it also drop lots of commented code that either was for debugging or belonged to features not present or used any more.

### CODE REVIEW

**Comment by infirit** [comment]
If there are things that bugs you let's just skip them for now and revisit them later (I promise I will not be offended so don't hold back 😄).

What I'll do is merge the simple things like white-space and comment formatting first. I'll leave the renames of functions and classes out for now.

**Comment by cschramm** [comment]
> I'll leave the renames of functions and classes out for now.

Well, I guess just testing with those changes is the only good way to discover issues...

**Comment by cschramm** [comment]
Shall we get this into 2.1.alpha2?

**Comment by infirit** [comment]
Its very out of sync and rebasing will take some time.

**Comment by infirit** [comment]
See #810

**Pull request closed without merging**
