### PR TITLE
Fix bluetoothd start/stop blueman crash

### LINKED ISSUE #1231: blueman-manager crashes when bluetoothd is restarted
**Environment**

blueman: `1:2.1.2-1.fc31`
BlueZ: `5.54-1.fc31`
Distribution: Fedora 31
Desktop environment: gnome

**The issue**

When restarting bluetoothd (`systemctl restart bluetooth.service`), `blueman-manager` crashes:
```
...
blueman-manager 12.42.06 DEBUG    Base:74 do_g_properties_changed: /org/bluez/hci0 {'Powered': False, 'Discovering': False, 'Class': 0}
blueman-manager 12.42.06 DEBUG    Manager:66 _on_object_removed: /org/bluez/hci0/dev_0C_A6_94_7D_B3_03
blueman-manager 12.42.06 DEBUG    Manager:66 _on_object_removed: /org/bluez/hci0/dev_38_18_4C_D3_19_E8
blueman-manager 12.42.06 DEBUG    Manager:66 _on_object_removed: /org/bluez/hci0/dev_00_22_37_46_50_2E
blueman-manager 12.42.06 DEBUG    Manager:62 _on_object_removed: /org/bluez/hci0
blueman-manager 12.42.06 DEBUG    DeviceList:238 set_adapter: Setting adapter to: None
blueman-manager 12.42.06 DEBUG    ManagerToolbar:62 on_adapter_changed: toolbar adapter None
blueman-manager 12.42.06 INFO     Manager:82 on_dbus_name_vanished: org.bluez
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 1: invalid start byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 3: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 3: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
blueman-manager 12.42.06 INFO     Manager:102 on_dbus_name_appeared: org.bluez :1.2393
blueman-manager 12.42.06 ERROR    Manager:118 on_dbus_name_appeared: Default adapter not found, trying first available.
blueman-manager 12.42.06 ERROR    Manager:122 on_dbus_name_appeared: No adapter(s) found, exiting
blueman-manager 12.42.06 INFO     PulseAudioUtils:669 _on_delete: Destroying PulseAudioUtils instance
...
```

This is especially annoying as my initramfs is locking my encrypted luks `/` volume and chrooting into the initramfs to ensure data security. To do that, it need to `systemctl stop bluetooth` before suspending, and `systemctl start bluetooth` while resuming, because bluetoothd can otherwise inhibit the suspend process as it generates i/o on the locked encrypted root volume.

This means that blueman-manager crashes after every suspend.

**Suggested solution** 

Simply show "no bluetooth adapter found" in blueman-manager.
I found [this](https://github.com/blueman-project/blueman/blob/master/blueman/main/Manager.py#L100) FIXME, which seems related to this:  
> FIXME ui can handle BlueZ start/stop but we should inform user

### PR DESCRIPTION
**Pull request by Yannik**
Fixes #1231

### CODE REVIEW

**Comment by infirit** [comment]
With the signal handler problem fixed I see no crash. It properly closes as intended. If you do get a crash provide the log for ``blueman-manager --loglevel debug``.

As per the FIXME the UI can handle this but we need to inform the user. I see nothing in this PR that informs the user.

**Comment by Yannik** [comment]
@infirit I think it's logged as crash by fedora because of the `exit(1)`.

Anyway, I don't think that the current behavior of blueman-manager suddenly closing after/during a suspend is desirable. 

>As per the FIXME the UI can handle this but we need to inform the user. I see nothing in this PR that informs the user. 

Quoting [this](https://github.com/blueman-project/blueman/issues/1231#issuecomment-619978737):

> With my patch, when no adapter is available, no devices are shown and the adapter menu is greyed out. I think this is a pretty good indication that the bluetooth adapter is not available (plus there's always the stdout/stderr output). Adding an extra frame like you suggested seems like a nice suggestion though. What about opening another issue to track this?
> 
> I'd like to keep this separate because this PR is targeted at fixing the crash on suspend, which seems like the higher priority.

**Comment by infirit** [comment]
Our usage of exit(1) is probably not right here. We shouldn't be using it in production code anyway. I'll send a pr to replace all of them with SystemExit

**Comment by infirit** [comment]
As mentioned, I really like to see the user notified properly. The crash report should be gone now by not using exitcode 1.

**Comment by Yannik** [comment]
@cschramm Has this been fixed? I.e. no force-close on standby (with bluetooth getting disabled during the standby procedure) anymore?

**Comment by cschramm** [comment]
I got confused by all the interleaved topics, so I'm not sure, but this PR says it fixes #1231 and #1231 is already closed (by #1234).

**Pull request closed without merging**
