### PR TITLE
Use ModelFilter for the TreeView

### PR DESCRIPTION
**Pull request by infirit**
Still need to iron out some bugs here and there. This should help with #1621 if the Name/Alias is updated after initial InterfaceAdded.

### CODE REVIEW

**Comment by infirit** [comment]
Struggling with the the typing of the model. The problem I am running into is that the model can be any of type `Gtk.ListStore`, `Gtk.TreeStore` or `Gtk.TeeModelSort`. `Gtk.TeeModelSort` implements the convert function which are needed to convert iters/paths to the child equivalent and back.

If I explicitly type annotate the model with `Gtk.TeeModelSort` mypy complains it isn't a `Gtk.TreeModel` if I don't mypy complains that `Gtk.TreeModel` does not have the convert functions. 

Tried updating the `Gtk.pyi` to have `typing.Type[TreeModel]`, no joy
Tried replacing the `TreeModel` in `Gtk.pyi` with a `typing.Union` of all the model implementations, no joy.

Pretty much stuck here :cry:

**Comment by cschramm** [comment]
I think it's actually `TreeModelFilter`, not `TreeModelSort`, but that does not change the problem.

Complete solution with generic `TreeView` and `TreeSelection`:
<details>

```diff
diff --git a/blueman/gui/DeviceList.py b/blueman/gui/DeviceList.py
index 7d3caa37..e999e8ff 100644
--- a/blueman/gui/DeviceList.py
+++ b/blueman/gui/DeviceList.py
@@ -125,7 +125,7 @@ class DeviceList(GenericList):
 
                 self.device_remove_event(dev)
 
-    def on_selection_changed(self, selection: Gtk.TreeSelection) -> None:
+    def on_selection_changed(self, selection: Gtk.TreeSelection[Gtk.TreeModelFilter]) -> None:
         model, tree_iter = selection.get_selected()
         if tree_iter:
             tree_iter = model.convert_iter_to_child_iter(tree_iter)
diff --git a/blueman/gui/DeviceSelectorDialog.py b/blueman/gui/DeviceSelectorDialog.py
index 5d17c1eb..aa0163a4 100644
--- a/blueman/gui/DeviceSelectorDialog.py
+++ b/blueman/gui/DeviceSelectorDialog.py
@@ -38,8 +38,8 @@ class DeviceSelectorDialog(Gtk.Dialog):
         self.selector.destroy()
         super().close()
 
-    def on_row_activated(self, _treeview: Gtk.TreeView, _path: Gtk.TreePath, _view_column: Gtk.TreeViewColumn,
-                         *_args: object) -> None:
+    def on_row_activated(self, _treeview: Gtk.TreeView[Gtk.TreeModelFilter], _path: Gtk.TreePath,
+                         _view_column: Gtk.TreeViewColumn, *_args: object) -> None:
         self.response(Gtk.ResponseType.ACCEPT)
 
     def on_adapter_changed(self, _devlist: DeviceList, _adapter: str) -> None:
diff --git a/blueman/gui/GenericList.py b/blueman/gui/GenericList.py
index 20896d2c..d0baff00 100644
--- a/blueman/gui/GenericList.py
+++ b/blueman/gui/GenericList.py
@@ -16,14 +16,14 @@ if TYPE_CHECKING:
         renderer: Gtk.CellRenderer
         render_attrs: Mapping[str, int]
         view_props: Mapping[str, object]
-        celldata_func: Tuple[Callable[[Gtk.TreeViewColumn, Gtk.CellRenderer, Gtk.TreeModel, Gtk.TreeIter, Any],
+        celldata_func: Tuple[Callable[[Gtk.TreeViewColumn, Gtk.CellRenderer, Gtk.TreeModelFilter, Gtk.TreeIter, Any],
                                       None], Any]
 else:
     ListDataDict = dict
 
 
 # noinspection PyAttributeOutsideInit
-class GenericList(Gtk.TreeView):
+class GenericList(Gtk.TreeView[Gtk.TreeModelFilter]):
     def __init__(self, data: Iterable[ListDataDict], headers_visible: bool = True, visible: bool = False) -> None:
         super().__init__(headers_visible=headers_visible, visible=visible)
         self.set_name("GenericList")
diff --git a/blueman/gui/applet/PluginDialog.py b/blueman/gui/applet/PluginDialog.py
index 8c77017b..e935e1ab 100644
--- a/blueman/gui/applet/PluginDialog.py
+++ b/blueman/gui/applet/PluginDialog.py
@@ -187,7 +187,7 @@ class PluginDialog(Gtk.Window):
         self.applet.Plugins.disconnect(self.sig_b)
         return False
 
-    def on_selection_changed(self, selection: Gtk.TreeSelection) -> None:
+    def on_selection_changed(self, selection: Gtk.TreeSelection[Gtk.TreeModelFilter]) -> None:
         model, tree_iter = selection.get_selected()
         assert tree_iter is not None
 
diff --git a/blueman/gui/manager/ManagerDeviceList.py b/blueman/gui/manager/ManagerDeviceList.py
index c8b04f6c..9fbf2283 100644
--- a/blueman/gui/manager/ManagerDeviceList.py
+++ b/blueman/gui/manager/ManagerDeviceList.py
@@ -593,7 +593,7 @@ class ManagerDeviceList(DeviceList):
                 return True
         return False
 
-    def _set_cell_data(self, _col: Gtk.TreeViewColumn, cell: Gtk.CellRenderer, model: Gtk.TreeModel,
+    def _set_cell_data(self, _col: Gtk.TreeViewColumn, cell: Gtk.CellRenderer, model: Gtk.TreeModelFilter,
                        tree_iter: Gtk.TreeIter, data: Optional[str]) -> None:
         tree_iter = model.convert_iter_to_child_iter(tree_iter)
         if data is None:
diff --git a/blueman/main/Services.py b/blueman/main/Services.py
index 1f31501b..5323a3d9 100644
--- a/blueman/main/Services.py
+++ b/blueman/main/Services.py
@@ -132,7 +132,7 @@ class BluemanServices(Gtk.Application):
             else:
                 inst._on_leave()
 
-    def on_selection_changed(self, _selection: Gtk.TreeSelection) -> None:
+    def on_selection_changed(self, _selection: Gtk.TreeSelection[Gtk.TreeModelFilter]) -> None:
         tree_iter = self.List.selected()
         assert tree_iter
         if self.List.get_cursor()[0]:
diff --git a/stubs/gi/repository/Gtk.pyi b/stubs/gi/repository/Gtk.pyi
index 2f76c8b1..2a5d0821 100644
--- a/stubs/gi/repository/Gtk.pyi
+++ b/stubs/gi/repository/Gtk.pyi
@@ -2396,7 +2396,7 @@ class TreeModel(GObject.GInterface):
 
     def __getitem__(self, key: typing.Union[TreePath, int, str]) -> TreeModelRow: ...
 
-    def filter_new(self, root: typing.Optional[TreePath] = None) -> TreeModel: ...
+    def filter_new(self, root: typing.Optional[TreePath] = None) -> TreeModelFilter: ...
 
     def foreach(self, func: TreeModelForeachFunc, *user_data: typing.Optional[builtins.object]) -> None: ...
 
@@ -2486,19 +2486,20 @@ class TreeModel(GObject.GInterface):
 
     def do_unref_node(self, iter: TreeIter) -> None: ...
 
+_T = typing.TypeVar("_T", bound=TreeModel)
 
-class TreeSelection(GObject.Object):
+class TreeSelection(GObject.Object, typing.Generic[_T]):
     parent: GObject.Object
 
     def count_selected_rows(self) -> builtins.int: ...
 
     def get_mode(self) -> SelectionMode: ...
 
-    def get_selected(self) -> typing.Tuple[TreeModel, typing.Optional[TreeIter]]: ...
+    def get_selected(self) -> typing.Tuple[_T, typing.Optional[TreeIter]]: ...
 
-    def get_selected_rows(self) -> typing.Tuple[TreeModel, typing.Sequence[TreePath]]: ...
+    def get_selected_rows(self) -> typing.Tuple[_T, typing.Sequence[TreePath]]: ...
 
-    def get_tree_view(self) -> TreeView: ...
+    def get_tree_view(self) -> TreeView[_T]: ...
 
     def iter_is_selected(self, iter: TreeIter) -> builtins.bool: ...
 
@@ -6655,19 +6656,21 @@ class Toolbar(Container, Orientable, ToolShell):
     def do_style_changed(self, style: ToolbarStyle) -> None: ...
 
 
-class TreeView(Container, Scrollable):
+class TreeView(Container, Scrollable, typing.Generic[_T]):
     parent: Container
 
-    class _Props(Container._Props):
+    _PT = typing.TypeVar("_PT", bound=TreeModel)
+
+    class _Props(Container._Props, typing.Generic[_PT]):
         headers_visible: bool
-        model: typing.Optional[TreeModel]
+        model: typing.Optional[TreeView._PT]
 
-    props: _Props
+    props: _Props[_T]
 
     def __init__(self,
         *,
         headers_visible: bool = True,
-        model: typing.Optional[TreeModel] = None,
+        model: typing.Optional[_T] = None,
         # Container
         border_width: int = 0,
         # Widget
@@ -6761,7 +6764,7 @@ class TreeView(Container, Scrollable):
 
     def get_level_indentation(self) -> builtins.int: ...
 
-    def get_model(self) -> typing.Optional[TreeModel]: ...
+    def get_model(self) -> typing.Optional[_T]: ...
 
     def get_n_columns(self) -> builtins.int: ...
 
@@ -6777,13 +6780,13 @@ class TreeView(Container, Scrollable):
 
     def get_search_entry(self) -> Entry: ...
 
-    def get_selection(self) -> TreeSelection: ...
+    def get_selection(self) -> TreeSelection[_T]: ...
 
     def get_show_expanders(self) -> builtins.bool: ...
 
     def get_tooltip_column(self) -> builtins.int: ...
 
-    def get_tooltip_context(self, x: builtins.int, y: builtins.int, keyboard_tip: builtins.bool) -> typing.Tuple[builtins.bool, builtins.int, builtins.int, typing.Optional[TreeModel], TreePath, TreeIter]: ...
+    def get_tooltip_context(self, x: builtins.int, y: builtins.int, keyboard_tip: builtins.bool) -> typing.Tuple[builtins.bool, builtins.int, builtins.int, typing.Optional[_T], TreePath, TreeIter]: ...
 
     def get_vadjustment(self) -> Adjustment: ...
 
@@ -6807,7 +6810,7 @@ class TreeView(Container, Scrollable):
     def new() -> Widget: ...
 
     @staticmethod
-    def new_with_model(model: TreeModel) -> Widget: ...
+    def new_with_model(model: _T) -> Widget: ...
 
     def remove_column(self, column: TreeViewColumn) -> builtins.int: ...
 
@@ -6853,7 +6856,7 @@ class TreeView(Container, Scrollable):
 
     def set_level_indentation(self, indentation: builtins.int) -> None: ...
 
-    def set_model(self, model: typing.Optional[TreeModel]) -> None: ...
+    def set_model(self, model: typing.Optional[_T]) -> None: ...
 
     def set_reorderable(self, reorderable: builtins.bool) -> None: ...
 
@@ -6867,7 +6870,7 @@ class TreeView(Container, Scrollable):
 
     def set_search_entry(self, entry: typing.Optional[Entry]) -> None: ...
 
-    def set_search_equal_func(self, search_equal_func: typing.Callable[[TreeModel, int, str, TreeIter], bool], *search_user_data: typing.Optional[builtins.object]) -> None: ...
+    def set_search_equal_func(self, search_equal_func: typing.Callable[[_T, int, str, TreeIter], bool], *search_user_data: typing.Optional[builtins.object]) -> None: ...
 
     def set_search_position_func(self, func: typing.Optional[TreeViewSearchPositionFunc], *data: typing.Optional[builtins.object]) -> None: ...
 ```
</details>

Minimal solution based on the fact that our `TreeView` and `TreeSelection` *always* handle a `TreeModelFilter`, so that we know that `get_selected` will always return one and `TreeCellDataFunc` will always receive one:

<details>

```diff
diff --git a/blueman/gui/GenericList.py b/blueman/gui/GenericList.py
index 20896d2c..29fe7348 100644
--- a/blueman/gui/GenericList.py
+++ b/blueman/gui/GenericList.py
@@ -16,7 +16,7 @@ if TYPE_CHECKING:
         renderer: Gtk.CellRenderer
         render_attrs: Mapping[str, int]
         view_props: Mapping[str, object]
-        celldata_func: Tuple[Callable[[Gtk.TreeViewColumn, Gtk.CellRenderer, Gtk.TreeModel, Gtk.TreeIter, Any],
+        celldata_func: Tuple[Callable[[Gtk.TreeViewColumn, Gtk.CellRenderer, Gtk.TreeModelFilter, Gtk.TreeIter, Any],
                                       None], Any]
 else:
     ListDataDict = dict
diff --git a/blueman/gui/manager/ManagerDeviceList.py b/blueman/gui/manager/ManagerDeviceList.py
index c8b04f6c..9fbf2283 100644
--- a/blueman/gui/manager/ManagerDeviceList.py
+++ b/blueman/gui/manager/ManagerDeviceList.py
@@ -593,7 +593,7 @@ class ManagerDeviceList(DeviceList):
                 return True
         return False
 
-    def _set_cell_data(self, _col: Gtk.TreeViewColumn, cell: Gtk.CellRenderer, model: Gtk.TreeModel,
+    def _set_cell_data(self, _col: Gtk.TreeViewColumn, cell: Gtk.CellRenderer, model: Gtk.TreeModelFilter,
                        tree_iter: Gtk.TreeIter, data: Optional[str]) -> None:
         tree_iter = model.convert_iter_to_child_iter(tree_iter)
         if data is None:
diff --git a/stubs/gi/repository/Gtk.pyi b/stubs/gi/repository/Gtk.pyi
index 2f76c8b1..56c4369f 100644
--- a/stubs/gi/repository/Gtk.pyi
+++ b/stubs/gi/repository/Gtk.pyi
@@ -2396,7 +2396,7 @@ class TreeModel(GObject.GInterface):
 
     def __getitem__(self, key: typing.Union[TreePath, int, str]) -> TreeModelRow: ...
 
-    def filter_new(self, root: typing.Optional[TreePath] = None) -> TreeModel: ...
+    def filter_new(self, root: typing.Optional[TreePath] = None) -> TreeModelFilter: ...
 
     def foreach(self, func: TreeModelForeachFunc, *user_data: typing.Optional[builtins.object]) -> None: ...
 
@@ -2494,7 +2494,7 @@ class TreeSelection(GObject.Object):
 
     def get_mode(self) -> SelectionMode: ...
 
-    def get_selected(self) -> typing.Tuple[TreeModel, typing.Optional[TreeIter]]: ...
+    def get_selected(self) -> typing.Tuple[TreeModelFilter, typing.Optional[TreeIter]]: ...
 
     def get_selected_rows(self) -> typing.Tuple[TreeModel, typing.Sequence[TreePath]]: ...
 
@@ -12366,7 +12366,7 @@ TextCharPredicate = typing.Callable[[builtins.str, typing.Optional[builtins.obje
 TextTagTableForeach = typing.Callable[[TextTag, typing.Optional[builtins.object]], None]
 TickCallback = typing.Callable[[Widget, Gdk.FrameClock, typing.Optional[builtins.object]], builtins.bool]
 TranslateFunc = typing.Callable[[builtins.str, typing.Optional[builtins.object]], builtins.str]
-TreeCellDataFunc = typing.Callable[[TreeViewColumn, CellRenderer, TreeModel, TreeIter, typing.Optional[builtins.object]], None]
+TreeCellDataFunc = typing.Callable[[TreeViewColumn, CellRenderer, TreeModelFilter, TreeIter, typing.Optional[builtins.object]], None]
 TreeDestroyCountFunc = typing.Callable[[TreeView, TreePath, builtins.int, typing.Optional[builtins.object]], None]
 TreeIterCompareFunc = typing.Callable[[TreeModel, TreeIter, TreeIter, typing.Optional[builtins.object]], builtins.int]
 TreeModelFilterModifyFunc = typing.Callable[[TreeModel, TreeIter, builtins.int, typing.Optional[builtins.object]], GObject.Value]
```
</details>

Independent of the solution:

* Although [its documentation](https://docs.gtk.org/gtk3/method.TreeModel.filter_new.html) does not even mention `TreeModelFilter`, it seems obvious that `TreeModel.filter_new` always returns one. :shrug:
* You call a couple of methods with an `Optional[TreePath]` where they expect a `TreePath`. You'll have to put the `Optional[TreePath]` into a variable - say `path` - (if it's not stored in one already) and `assert path is not None` to make them a non-optional `TreePath`. Cases where the values are non, depending on the methods they come from:
  * `TreeRowReference.get_path`: _the path pointed to is no longer valid_
  * `TreeModelFilter.convert_path_to_child_path`: _`filter_path` does not point to a location in the child model_

**Comment by cschramm** [comment]
...I'm trying to remember why I avoided generics a couple of times... :thinking: Maybe just for maintaining compatibility with Python 3.3 and 3.4 but there might be another problem I forgot about. :grimacing:

**Comment by infirit** [comment]
Yeah, meant ModelFilter. I'll try out the complete option and only have minimal changes in Gtk.pyi.

Thanks!

**Comment by infirit** [comment]
Ah, forgot I had this one open :disappointed: . I'll rebase and fix those typing issues asap.

**Comment by infirit** [comment]
typing gives me headaches, but it's done. I went with the minimal typing change that only works for blueman.

**Review by cschramm — APPROVED** [review]
👍 Guess it deserves a changelog entry.

**Pull request merged**
