### PR TITLE
Update CHANGELOG and time for an alpha?

### PR DESCRIPTION
**Pull request by infirit**
Doing a PR so we can have a quick discussion whether it is time to do a first alpha release. So much has changed so it would be good if it got some more exposure.

If not what do you think should be done before that can happen?

### CODE REVIEW

**Comment by infirit** [comment]
Ah, crap merged it somehow, oh well, we can still have the discussion :smile:

**Comment by cschramm** [comment]
:smile: I agree we can target a prerelease version sometime soon.

I started working on #10 a couple of weeks ago, but did not find the time to continue yet. I really want to get that feature in, just because it was kind of the very first item I scheduled for a 2.1 version, long before 2.0 was ready. :laughing:  Another interesting improvement for 2.1 is #415 I think.

I'll try to finish #10 asap.

**Comment by cschramm** [comment]
Sorry for blocking this so long... Can you get the changelog up to date?

**Comment by infirit** [comment]
Updated the changelog :smile:

**Pull request merged**
