### PR TITLE
Re-implementation of NM Pan support with GDBus proxy objects

### PR DESCRIPTION
**Pull request by infirit**
Direct translation to GDBus ended up being quite ugly so decided to rewrite using actual GDBusProxy objects connecting to the signals. The goals is to not use the NewConnectionBuilder class and it will be removed.  This is not meant to be merged, just to put what I have done so far out there so people know about it.

### CODE REVIEW

**Comment by infirit** [comment]
Updated, not working yet, but we are getting somewhere. Took me a bit of time to figure NetworkManager out but we got it now.

**Comment by infirit** [comment]
Ok, this is pretty much finished except that there is an annoying bug which I am confused about :confused:.

"Something" appears to initiate the network manager connection outside of the [service_connect_handler](https://github.com/blueman-project/blueman/pull/544/commits/db1f6573853fc30c51213de4e71a1358b05e8464#diff-5b460f3488fed97a2f213612fe0b466dR312) and as a result when I call ``ActivateConnection`` on NetworkManager the proxy returns that the connection is already in progress.

```
fail (/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:126)
fail g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.blueman.bluez.errors.DBusInProgressError: DBusInProgressError:  Operation already in progress
```

Commenting out the ``ActivateConnection`` line I do see the connection states progress and either fail or succeed. I am properly confused by this and if anybody has ideas what is going on do reply here :smiley:

**Comment by cschramm** [comment]
Hm... It doesn't look like the old code catches that somehow. I think it would always run `ActivateConnection` for BlueZ 5 unless it runs into the `Network Manager did not support the connection` case. Do you still have your code of the "Direct translation to GDBus" to check if that suffers from the same problem?

**Comment by infirit** [comment]
> I think it would always run ActivateConnection for BlueZ 5 

Yes, trying to disconnect it will result in an error saying the connection was not activated.

>Do you still have your code of the "Direct translation to GDBus" to check if that suffers from the same problem?

No but I'll do that now to see if that does work ok. I was really happy with the NMDevice class though but if I can't get it to work.. :smile:

**Comment by infirit** [comment]
Completely untested but here is the direct translation to GDBus in my [nm_gdbus_direct](https://github.com/infirit/blueman/tree/nm_gdbus_direct) branch.

**Comment by infirit** [comment]
Learned a lot from trying to re-implment this but see  #567

**Pull request closed without merging**
