### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by infirit**
This is my work in progress moving from dprint to the python logging module.

We should take this opertunity to also review the message we log.
 * Are they still relevant?
 * Should we revise the text? 
 * Is the current level correct (debug, warning, info etc)
 * Anything more?

ps: this also includes the argparse port

edit: updated 27-12-2016

### CODE REVIEW

**Comment by infirit** [comment]
Removed WIP as it works pretty well for me now. Now we need to review 😨

**Comment by infirit** [comment]
Really happy to see thing like below 😄.

```python
Stale PID, overwriting
blueman-manager 17.08.07 ERROR    ManagerDeviceList:338 level_setup_event: Read RSSI failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 336, in level_setup_event
    rssi = float(cinfo.get_rssi())
  File "_blueman.pyx", line 282, in _blueman.conn_info.get_rssi (_blueman.c:3574)
Exception: Read RSSI failed
blueman-manager 17.08.07 ERROR    ManagerDeviceList:343 level_setup_event: Read Link quality failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 341, in level_setup_event
    lq = float(cinfo.get_lq())
  File "_blueman.pyx", line 290, in _blueman.conn_info.get_lq (_blueman.c:3688)
Exception: Read Link quality failed
blueman-manager 17.08.07 ERROR    ManagerDeviceList:349 level_setup_event: Read transmit power level request failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 347, in level_setup_event
    tpl = float(cinfo.get_tpl())
  File "_blueman.pyx", line 298, in _blueman.conn_info.get_tpl (_blueman.c:3845)
Exception: Read transmit power level request failed
```

**Comment by infirit** [comment]
Example 😄 

```python
Stale PID, overwriting
blueman-manager 17.08.07 ERROR    ManagerDeviceList:338 level_setup_event: Read RSSI failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 336, in level_setup_event
    rssi = float(cinfo.get_rssi())
  File "_blueman.pyx", line 282, in _blueman.conn_info.get_rssi (_blueman.c:3574)
Exception: Read RSSI failed
blueman-manager 17.08.07 ERROR    ManagerDeviceList:343 level_setup_event: Read Link quality failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 341, in level_setup_event
    lq = float(cinfo.get_lq())
  File "_blueman.pyx", line 290, in _blueman.conn_info.get_lq (_blueman.c:3688)
Exception: Read Link quality failed
blueman-manager 17.08.07 ERROR    ManagerDeviceList:349 level_setup_event: Read transmit power level request failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 347, in level_setup_event
    tpl = float(cinfo.get_tpl())
  File "_blueman.pyx", line 298, in _blueman.conn_info.get_tpl (_blueman.c:3845)
Exception: Read transmit power level request failed
```

**Comment by cschramm** [comment]
Awesome! Looks good. (I obviously did not review every single message though.)

**Comment by infirit** [comment]
Merged this one finally, let me know if things are not correct or not working to your liking 😄 .

**Pull request merged**
