### PR TITLE
Update version in meson.build

### PR DESCRIPTION
**Pull request by infirit**
The rest appears to still works properly so just the version bump.

### CODE REVIEW

**Comment by cschramm** [comment]
:thinking: The CircleCI builds did not get triggered...

**Comment by infirit** [comment]
It completed on circleci but it did not show in github. This happens a lot for me, mostly on master for some reason 😞

**Comment by cschramm** [comment]
Waait a second... Builds for my pull requests get triggered in https://circleci.com/gh/blueman-project/blueman while this one got triggered in https://circleci.com/gh/infirit/blueman.

My guess: As you have set up https://circleci.com/gh/infirit/blueman commits that you push to https://github.com/infirit/blueman/ first, get built there and not in https://circleci.com/gh/blueman-project/blueman and cannot report to https://github.com/blueman-project/blueman.

I guess you should drop your personal blueman CircleCI project to fix the issues.

**Comment by infirit** [comment]
Its intermittent, sometimes its fine but other times it just does not want to report back. I restarted it and then it was fine. If it becomes unbearable I'll see if disabling it on my personal account makes a difference.

**Pull request merged**
