### PR TITLE
Backport rename of random pass key to 2.0 branch

### PR DESCRIPTION
**Pull request by rworkman**
This is a backport of 4fc3a8facbc09e0820bacea28e6a379e3065c975

### CODE REVIEW

**Comment by rworkman** [comment]
I don't see how this would make the build test fail - it's fine here, and besides, the error shown in the build test output seems unrelated...

**Comment by cschramm** [comment]
Looks good to me, but please add a changelog entry.

The build seems to broken on the new travis machines, but I did not care about it for a while as it does not work for master (i.e. BlueZ 5 only) anyway.

**Comment by rworkman** [comment]
CHANGELOG.md entry added, squashed/fixup'd and force pushed.

**Comment by rworkman** [comment]
There are some other commits backported or cherry-picked from master in this branch now; if that complicates the merging, I can put them into separate branches and do separate pull requests for them. Please review - in my local testing, everything seems fine (on bluez-5.x here now), but I'd feel better about shoving them into a -stable branch if they were once-over'd by you guys...

**Comment by cschramm** [comment]
Looks all good to me.

**Comment by infirit** [comment]
Those changes make sense for 2.0. Just curious about the changed commit message (example below). Is there a reason for this? Normally ``git cherry-pick`` does not do this.

```
Backport of cdcf465 in master

Signed-off-by: Robby Workman <rworkman@slackware.com>
```

**Comment by rworkman** [comment]
It wouldn't cherry-pick cleanly, and since it was a small diff, it was easier to make the changes manually and do a commit that way.

**Comment by rworkman** [comment]
So what's the verdict? Is there anything else I need to do in order to make these acceptable?

**Comment by cschramm** [comment]
No, sorry, merged now. :smiley:

**Pull request merged**
