### PR TITLE
Use pgrep to check for running processes

### PR DESCRIPTION
**Pull request by infirit**
Untested, see https://github.com/blueman-project/blueman/issues/524#issuecomment-220964106

### CODE REVIEW

**Comment by infirit** [comment]
Added another commit for PPPSupport to change the binary name to ModemManager.

**Comment by infirit** [comment]
Tested now, seems to work nicely. As usual, I have no DUN phone to test the modem manager changes.

**Comment by cschramm** [comment]
Adds procps as a dependency. Fine with that.

Why `modem-manager` -> `ModemManager`?

**Comment by infirit** [comment]
The binary is named like that on my system and my debian vm. It was done already in [2012](https://cgit.freedesktop.org/ModemManager/ModemManager/commit/?id=7d9d003324bb6a466104c7d935758ca29aeac9e5)

**Comment by infirit** [comment]
>Adds procps as a dependency

btw, I can also fix the grep without ``pgrep``. Simply adding brackets around a single letter and it will exclude the grep process. Either way is fine with me :smile:

**Comment by cschramm** [comment]
> The binary is named like that

Looks like it, yes. I did not run into that as #526 drops the name anyway. I guess if we land that, there's no reason for this patch anymore, right?

**Comment by infirit** [comment]
>I guess if we land that, there's no reason for this patch anymore, right?

Yep, but I do like to put this in 2.0 which will not get #526. I'll open a new PR without adding the procps dep.

**Comment by infirit** [comment]
Closing, #526 gets rid of these bits.

**Pull request closed without merging**
