### PR TITLE
RFC: GtkAnimation: Fix CellFade fading

### PR DESCRIPTION
**Pull request by infirit**
Recently I was looking at the old gtk2 blueman version in Ubuntu 14.04. And unfortunately the move to Gtk3/GI broke most of the fading. I fixed the TreeRow(Color)Fade, which leaves CellFade.

I have a partial fix but it is not perfect as the rows in the treeview have a slight gradient for me. Which means the are small color inconsistencies. I will keep poking at this to make it work properly but do we want to have it merged as it is now, imperfect as it is? Below is the commit message,

```
* Clip only after all rectangles are added to the cairo context
* Use background color as source color.

TODO: Background color is not completely correct but Gtk.render_background
does not work either..
```

### CODE REVIEW

**Comment by cschramm** [comment]
I think it's an improvement over the current state, isn't it?

**Comment by infirit** [comment]
Before it was very broken and  flashed to/from black, very ugly and noticeable. I then disabled the fading (current state).

It actually fades now in almost the right background so it is an improvement over that yes.

**Comment by cschramm** [comment]
So let's merge it. :smiley:

**Comment by infirit** [comment]
Merged :smile:

**Pull request merged**
