### PR TITLE
Fix release job

### PR DESCRIPTION
**Pull request by infirit**
I copied over what you did for check. Hopefully this is enough.

### CODE REVIEW

**Review by cschramm — APPROVED** [review]

**Comment by infirit** [comment]
Yeah, it works now. It generated a release from the tag I just pushed and it has everything autotools it should. Is there anything else you need merged? If not it's ready for release :smile:

**Comment by cschramm** [comment]
Lgtm. :+1:

**Comment by infirit** [comment]
I am happy to publish it, I can understand if your don't :-).

**Comment by cschramm** [comment]
Do it! :smile:

**Comment by infirit** [comment]
It is done. It appears I can't create anouncements. Can you make one?

**Comment by cschramm** [comment]
Hm. Looks like it's not possible after the release. At least I cannot find any option to do it. (I can create an announcement of course, but not tie it to the release.)

**Pull request merged**
