### PR TITLE
configure: added --with-systemd-userunitdir and... 

### PR DESCRIPTION
**Pull request by yars068**
...--with-systemd-systemunitdir options.

P.S. How to edit existing pull-requests, instead of creating new one?

### CODE REVIEW

**Comment by infirit** [comment]
Try https://github.com/infirit/blueman/commit/df0c2097be8bb9f083f25d99f8de970de6987bdd.

**Comment by yars068** [comment]
Yor suggestion is simpler than my, but what if need to specify system and user units directories separately?

**Comment by infirit** [comment]
Do you have a system where this is the case? afaik it is not allowed and all unit files go into ``$prefix/lib/systemd/``

**Comment by yars068** [comment]
Then, IMO, it does not make sense, to provide configurabre option to set up path to unit directories, but only to disable it.

**Comment by infirit** [comment]
I pushed the commit, thanks for reporting and the suggestion.

**Pull request closed without merging**
