### PR TITLE
Fixes from stable

### PR DESCRIPTION
**Pull request by infirit**

### CODE REVIEW

**Comment by infirit** [comment]
Picked the remaining commits that only exist in stable + extra dist the meson_options

**Comment by cschramm** [comment]
#2334 is missing

**Comment by infirit** [comment]
Added that one.

**Comment by cschramm** [comment]
#2364

**Comment by cschramm** [comment]
ping

**Comment by infirit** [comment]
Completely forgot about this one 😅 . I'll go over this over the weekend to make sure I didn't miss anything.

**Comment by infirit** [comment]
> #2364

Added this one and I don't see any others missing.

**Review by cschramm — APPROVED** [review]

**Pull request merged**
