### PR TITLE
Increase status icon visibility timeout

### PR DESCRIPTION
**Pull request by ar0n**
When turning bluetooth on using the applet the tray status icon flickers (disappears the re-appears). This is annoying when a user opens a menu when the visibility is set, the context menu freezes and covers that part of the screen. It cannot be closed only by killing the blueman-applet process.

Screenshot_2021-12-11_12-47-50

It seems to me, that turning the BL on, takes time for the power manager, so I've increased the delay.

```
blueman-applet 14.58.20 INFO     KillSwitch:106 io_event  : killswitch registered 31
blueman-applet 14.58.20 INFO     KillSwitch:122 io_event  : State: True
blueman-applet 14.58.20 INFO     PowerManager:178 update_power_state: off False | foff False | on True | current state True | new state True
<wait 1-2 seconds>
blueman-applet 14.58.21 DEBUG    Manager:42 _on_object_added: /org/bluez/hci0
blueman-applet 14.58.21 INFO     Applet:76 on_adapter_added: Adapter added /org/bluez/hci0
blueman-applet 14.58.21 INFO     RecentConns:107 initialize: rebuilding menu
```
This solves the problem for me.

### CODE REVIEW

**Comment by cschramm** [comment]
PowerManager doesn't actually do anything there. The delay is from unblocking a Bluetooth killswitch until the (first) adapter is fully available again. Could you check `dmesg` when turning Bluetooth back on? It should shed some light on the delay. I can absolutely imagine that one second is not enough for all cases, yes. A quick check on my current system shows about 400 ms until the adapter is operational, half of that for applying the firmware patch.

**Comment by infirit** [comment]
It would be good to see the blueman-applet debug log when this happens. Clearly we shouldn't have the menu in this state but without the log it's hard to see what is going on.

**Comment by ar0n** [comment]
Sorry for the delay ... I'm back again :)

@infirit unfortunately, starting blueman-tray with log level debug does not give much info:
```
$ blueman-tray --loglevel DEBUG
blueman-tray 18.26.43 DEBUG    Tray:24 _on_name_appeared: Applet started on name org.blueman.Applet, showing indicator
blueman-tray 18.26.43 INFO     Tray:28 _on_name_appeared: Using indicator "AppIndicator"
```
This is the single blueman-tray process running. Am I doing this wrong?

@cschramm After turning BT on using the tray applet this is the relevant part from dmesg:
```
[ 6342.464944] usb 1-10: new full-speed USB device number 7 using xhci_hcd
[ 6342.606245] usb 1-10: New USB device found, idVendor=8087, idProduct=0aaa, bcdDevice= 0.02
[ 6342.606252] usb 1-10: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 6342.609770] Bluetooth: hci0: Bootloader revision 0.1 build 42 week 52 2015
[ 6342.610750] Bluetooth: hci0: Device revision is 2
[ 6342.610754] Bluetooth: hci0: Secure boot is enabled
[ 6342.610756] Bluetooth: hci0: OTP lock is enabled
[ 6342.610758] Bluetooth: hci0: API lock is enabled
[ 6342.610760] Bluetooth: hci0: Debug lock is disabled
[ 6342.610763] Bluetooth: hci0: Minimum firmware build 1 week 10 2014
[ 6342.611324] Bluetooth: hci0: Found device firmware: intel/ibt-17-16-1.sfi
[ 6344.038938] Bluetooth: hci0: Waiting for firmware download to complete
[ 6344.039857] Bluetooth: hci0: Firmware loaded in 1397776 usecs
[ 6344.039869] Bluetooth: hci0: Waiting for device to boot
[ 6344.053937] Bluetooth: hci0: Device booted in 13746 usecs
[ 6344.053961] Bluetooth: hci0: Found Intel DDC parameters: intel/ibt-17-16-1.ddc
[ 6344.055828] Bluetooth: hci0: Applying Intel DDC parameters completed
[ 6344.058940] Bluetooth: hci0: Firmware revision 0.1 build 207 week 35 2021
```
Further investigating this, it turns out that a firmware is being downloaded to the chip by the kernel module (https://github.com/torvalds/linux/blob/a33f5c380c4bd3fa5278d690421b72052456d9fe/drivers/bluetooth/btintel.c#L1971), so my guess is that this is eating up the time here., but I'm no expert on this.

[ 6344.038938] Bluetooth: hci0: Waiting for firmware download to complete
[ 6344.039857] Bluetooth: hci0: Firmware loaded in **1397776 usecs**

**Comment by cschramm** [comment]
Ouch, so your firmware download takes 1.4 seconds and the overall delay will probably be somewhere between 1.5 and 2 seconds. I guess it's fine if we just wait for the 2.5 seconds that you propose. It's still relatively low so that it shouldn't confuse the user.

@infirit, second opinion? :smile:

**Comment by infirit** [comment]
> @infirit, second opinion?

Not really, 2,5 is a bit long but it also give some wiggle room for even worse adapters.

**Review by cschramm — APPROVED** [review]

**Pull request merged**
