### PR TITLE
Clicking the applet icon now toggles on/off blueman-manager.

### PR DESCRIPTION
**Pull request by DavidGriffith**
Using the suggested code in #315, here's my implementation.  Seems to work as intended.

### CODE REVIEW

**Comment by DavidGriffith** [comment]
It looks like the Travis CI test failed (for this and #309) because that testing environment's installations of Bluez and Gthreads are older than what Blueman now requires.

**Comment by cschramm** [comment]
Yes, don't care about travis. :wink:

**Comment by cschramm** [comment]
Looks good to me. I'll merge it in a couple of days.

**Comment by infirit** [comment]
I would change this into a single if/else block, something like below pseudo code.

''''python
if exists and get_pid and is_running:
    kill it
else:
    launch
''''

It's clearer IMO what is going on :smile:.

**Comment by cschramm** [comment]
The problem with that is that you need to use the return value of `exists` in `get_pid` and the return value of `get_pid` in `is_running` and `kill`, so you would need to call the same method twice or three times...

**Comment by infirit** [comment]
Sorry was not clear, (on the mobile).

Yes put the pid and the lockfile in variables, but use a single if/else block instead of three :smile:.

**Comment by yars068** [comment]
@infirit > Yes put the pid and the lockfile in variables, but use a single if/else block instead of three

:) As I see, this is not one three-if block in the code, see blueman.Functions.check_single_instance. IMO that may use as-is.

**Comment by DavidGriffith** [comment]
I don't understand what I should do here?  Copy what yars068 is showing me?

**Comment by yars068** [comment]
@DavidGriffith, notihng to do. This is just another realization of your functionality enhancement. If you like your realization, use it instead of my own.

**Comment by infirit** [comment]
Merged as d8bf0b89292a7573cf4f00c93891f1655f14029b slightly modified.

**Pull request closed without merging**
