### PR TITLE
l10n: Fix non-localized strings

### PR DESCRIPTION
**Pull request by clefebvre**
This fixes some of the issues related to l10n.

### CODE REVIEW

**Comment by clefebvre** [comment]
@cschramm I noticed a few other issues but I'm not sure how to fix them.

- Can you ask Weblate to sync po/? There are a lot of translations done there which aren't in github yet.
- The translations framework is archaic... the list of locales is hardcoded in LINGUAS, the list of source files is hardcoded in POTFILES.in, this is hard to maintain and results in forgotten locales/files. I know it's an industry standard to do it like that and it doesn't support wildcards...
- I didn't check the po/LINGUAS file to make sure it has all the locales supported/translated in Weblate.
- The po/POTFILES.in file is missing a huge number of .py files, possibly also .ui files. It needs to be updated.
- I didn't find out how to build/update the POT file. When I build using dpkg-buildpackage (I've got debian/ packaging in my debian branch) it doesn't trigger a POT update. It could be on my side in the packaging though. Does the POT file gets updated for you when you build blueman?

**Comment by infirit** [comment]
Weblate opens a pull request and pushes new changes. We let the new translations accumulate in there and merge them before release (stable) or when we feel like it in main. 

`blueman-pot` we update manually.

**Comment by infirit** [comment]
You accidentally dropped the keyboard accelerators from the buttons. Can you add them back?

**Comment by clefebvre** [comment]
Thanks @infirit they're back.

**Comment by clefebvre** [comment]
@infirit can you give me a command to update the POT? I tried the following but it fails for me:

```
./autogen.sh
make -C po blueman.pot-update
```

I'm interested in fixing POTFILES.IN a little bit, but I can't test it without regenerating the POT locally to make sure it picks up everything it should.

**Comment by cschramm** [comment]
Another solution to that is `CYTHONEXEC=cython3`.

There's also a job to update the potfile currently accumulating in #1711.

**Review by cschramm — APPROVED** [review]

**Comment by eli-schwartz** [comment]
> I didn't find out how to build/update the POT file. When I build using dpkg-buildpackage (I've got debian/ packaging in my debian branch) it doesn't trigger a POT update. It could be on my side in the packaging though. Does the POT file gets updated for you when you build blueman?

Updating pot files is generally not supposed to be done as part of building and installing the software... it's a maintainer target.

@infirit,

Yu may want to set `extra_args: ` in po/meson.build for --package-version, --msgid-bugs-address, --copyright-holder in order to align the output with what autotools generates.

**Comment by clefebvre** [comment]
OK, I think I'm done with translation fixes for now. I'll need to translate a bit more in Weblate once the POT is regenerated and updated there. Hopefully I didn't forget anything.

**Review by cschramm — APPROVED** [review]

**Pull request merged**
