### PR TITLE
rfcomm channel

### PR DESCRIPTION
**Pull request by infirit**

### CODE REVIEW

**Comment by cschramm** [comment]
Looks good to me. Still work in progress?

**Comment by infirit** [comment]
Not really wip anymore. Could use some testing on a few more serial/rfcomm devices 😄

**Comment by parkerlreed** [comment]
Seems to work fine here. 

rfcomm_channel branch

````
[parker@gpdpocket ~]$ DISPLAY=:0 blueman-applet 
blueman-applet version 2.1.alpha1 starting
Stale PID, overwriting
blueman-applet 19.31.04 ERROR    PluginManager:90 Load      : Unable to load plugin module AppIndicator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/blueman/plugins/applet/AppIndicator.py", line 6, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/blueman/main/PluginManager.py", line 88, in Load
    __import__(self.module_path.__name__ + ".%s" % plugin, None, None, [])
  File "/usr/lib/python3.6/site-packages/blueman/plugins/applet/AppIndicator.py", line 9, in <module>
    raise ImportError
ImportError
blueman-applet 19.31.04 WARNING  PluginManager:149 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 19.31.05 WARNING  PluginManager:149 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-manager version 2.1.alpha1 starting
/usr/lib/python3.6/site-packages/gi/overrides/GObject.py:553: Warning: gsignal.c:2641: instance '0x5570cee23110' has no handler with id '1529'
  return func(*args, **kwargs)
Service Name: Dev B
rfcomm channel: 1
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/usr/lib/python3.6/site-packages/blueman/gui/manager/ManagerProgressbar.py:155: Warning: Source ID 206 was not found when attempting to remove it
  GLib.source_remove(self.gsource)
````

I was then able to connect via picocom. (I may not be the best example since mine IS on channel 1 lol)

**Comment by cschramm** [comment]
Same here. Works fine but device uses channel 1 anyway.

Where's that `Service Name: Dev B` line comming from? It's not from our code, is it?

**Comment by infirit** [comment]
@parkerlreed 
>I was then able to connect via picocom. (I may not be the best example since mine IS on channel 1 lol)

One is not set anywhere now so it is a good test if you are still able to connect properly.

@cschramm 
>Where's that Service Name: Dev B line comming from? It's not from our code, is it?

It is (sdp_record_print) but I'll drop that as its not very useful.

**Pull request merged**
