### PR TITLE
Rename recent connections header

### LINKED ISSUE #2328: Regression 2.4: "Recent Connections" is empty
blueman: 2.4-1
BlueZ: 5.73-4
Distribution: arch
Desktop environment: wayland

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Updating from 2.3 to 2.4 introduced a regression having an empty list in the "Recent Connection" tab in the applet. Downgrading to 2.3 showed them again:

2.3:
bm-2 3 5

2.4:
bm-2 4 0

Either this or the idea was to remove "Recent Connections" completely as all audio profiles are now inlined?

### PR DESCRIPTION
**Pull request by cschramm**
I hope this makes things clearer and avoids confusion due to the change from 2.3 to 2.4.

Closes #2328

### CODE REVIEW

**Comment by infirit** [comment]
You dropped the accelerator in the string not sure if you intended this. If not let's do `Reconne_ct to…`

**Comment by cschramm** [comment]
I think an accelerator is pointless for the insensitive item, isn't it?

**Comment by infirit** [comment]
It doesn't which make me wonder why it was there in the first place lol.

**Comment by cschramm** [comment]
It used to make sense when the item had a submenu and we just didn't remove the accelerator (which also made sense to not mess up translations).

**Pull request merged**
