### PR TITLE
Russian translation corrections

### PR DESCRIPTION
**Pull request by kuraga**
1. Connecting/disconnecting (_подключение_/_отключение_, respectively) makes/destroys a connection (_соединение_).
2. Translation errors.
3. Grammar errors (e.g. single vs plural).
4. Mismatches (e.g. omit spaces).

### CODE REVIEW

**Comment by infirit** [comment]
Thanks for the corrections. The translations are manager in weblateb over at https://hosted.weblate.org/engage/blueman/.

Would you be willing and able to update the translation there? You can use GitHub login to get access to it

**Comment by kuraga** [comment]
Ok, seems like 94 suggestions have been imported. Thanks!

**Comment by kuraga** [comment]
@infirit ,
ok, seems like 94 suggestions have imported.
After resolving conflicts and applying some emergency corrections, 64 suggestions have left.
Thanks!

**Comment by infirit** [comment]
I saw the update from weblate for russsion translation. Not sure we will do a 2.3.6 release but if we do they should be in there. Definately in 2.4.

**Comment by kuraga** [comment]
@infirit , thanks! Could we ping somebody to revise suggestions?

**Comment by infirit** [comment]
> @infirit , thanks! Could we ping somebody to revise suggestions?

AFAIK we don't have any per language maintainers so I just accepted them.

**Comment by kuraga** [comment]
Thanks!

**Pull request closed without merging**
