### PR TITLE
Send hostname in DHCPClient

### LINKED ISSUE #237: Could blueman be made to work with udhcpc
Just a suggestion, but could blueman be made to work with udhcpc (busybox) for network connections?

### PR DESCRIPTION
**Pull request by cschramm**
Closes #237
Closes #258

### CODE REVIEW

**Comment by infirit** [comment]
Are the the ISC dhclient dhcpcd supposed to have these options? For me the man page is silent on -H/-h..

**Comment by cschramm** [comment]
My Debian dhcpcd 6.0.5 has -h, yes.
Unfortunately my isc-dhclient-4.3.1 does NOT have -H. :unamused: Guess I found it on the Internet: http://linux.die.net/man/8/dhclient

**Comment by infirit** [comment]
dhcpcd 6.0.5 is [roy's](http://roy.marples.name/projects/dhcpcd/index) not ISC so I guess we can not rely on this to be available except for udhcpc?

**Comment by cschramm** [comment]
Looks like it unfortunately...

**Comment by cschramm** [comment]
I removed those parameters leaving only the addition to udhcpc.

**Comment by cschramm** [comment]
Not sure why travis fails to find Python.h now. Maybe connected to https://www.traviscistatus.com/incidents/h91j8ft0qs2l.

**Comment by infirit** [comment]
It looks like the python include path is missing in the CFLAGS. The makefile and autoconf files look in order and it is probable the container is at fault.

**Comment by infirit** [comment]
Just checked my build and I have ```-I/usr/include/python2.7``` showing in my build log. This is missing in the build log of travis and the reason it can not find the header.

**Comment by cschramm** [comment]
Travis will start a rollback of their latest updates in 20 minutes. Guess that will fix the build.

**Comment by cschramm** [comment]
Yep. :smiley:

**Pull request closed without merging**
