### PR TITLE
This fixes the half of #235

### PR DESCRIPTION
**Pull request by rsm-imap-cc**
The auto connect stills not working, but the connection success with the "connect button".

### CODE REVIEW

**Comment by cschramm** [comment]
Thanks for the fix. I think we can remove the elif as it only handles a very unusual edge case now (path exists but is not a directory) and is probably not shown to the user anyway (see below).

Am I right that you - as a user - did not see the exception that is raised if the directory does not exist and only saw it when looking at the applet's output? Then I think we should make sure that the user does get a message if the directory cannot be created.

**Comment by rsm-imap-cc** [comment]
I'm not 100% of having understood your question but, I found the error by launching the applet by the terminal.

I think that you could let the elif. I really daub that some one have a file called "Public" but some times exceptions happens. For example I never use extensions, and I renamed my global dirs to avoid writing caps over the terminal.. !

**Comment by infirit** [comment]
This is not right, the code first ask xdg for the public folder and we should not need to second guess if it exists. If xdg gives a folder that is not created you have a broken setup.

I do think we should show an error dialog if later on for some reason the initially selected folder has gone away.

rsm-imap-cc <notifications@github.com> schreef op 3 april 2015 18:09:22 CEST:
>The auto connect stills not working, but the connection success with
>the "connect button".
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/blueman-project/blueman/pull/236
>
>-- Commit Summary --
>
>  * This fixes the half of #235
>
>-- File Changes --
>
>    M blueman/main/applet/Transfer.py (6)
>
>-- Patch Links --
>
>https://github.com/blueman-project/blueman/pull/236.patch
>https://github.com/blueman-project/blueman/pull/236.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/blueman-project/blueman/pull/236

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cschramm** [comment]
I agree. I think it's best to just display a localized version of the message that is currently implemented as an exception to the user.

**Comment by infirit** [comment]
I have a branch on my fork that adds a message dialog that warn the user, see https://github.com/infirit/blueman/commit/7e00f5eb7ace1fdd4bb7d0226229f5faa916b1a1. Important is that I still raise the Exception as we do not want to continue with the broken shared-path.

Let me know if this is acceptable and I'll push it into master.

**Comment by cschramm** [comment]
Looks good to me.

**Comment by infirit** [comment]
Thx, pushed and closing this one.

Thanks @rsm-imap-cc for reporting this problem.

**Pull request closed without merging**
