### PR TITLE
PowerManager: Update adapter_state on adapter power changes

### PR DESCRIPTION
**Pull request by infirit**
See github issue #691

### CODE REVIEW

**Comment by cschramm** [comment]
I don't think that's 100 % correct. If it's about two adapters that are not powered and you power one of them, you would set `adapter_state = True` while `get_adapter_state` would still return `False`. Maybe we should just use that method? 🤔

**Comment by infirit** [comment]
New approach is to call ``set_adapter_state`` which handles all adapters and it updates adapter_state when done. This does mean that if one is powered all are powered and the other way around.

**Comment by cschramm** [comment]
Not sure about the implications of that. Let's try.

**Comment by infirit** [comment]
I dug a bit deeper today. The actual problem is in ``RequestPowerState`` when ``self.UpdatePowerState()`` is never run after ``cb.check()``. ``cb.check()`` correctly calls ``set_adapter_state`` but for some reason ``GLib.source_remove(self.timer)`` causes problems, maybe ``cb.check()`` blocks, not sure yet but very likely. But I do know that when I comment ``GLib.source_remove(self.timer)`` out ``self.UpdatePowerState()`` is run. Hopefully have a proper fix later tonight.

**Comment by infirit** [comment]
It did not block so that was good to see. However the bug is very subtle and it was just that we ended up calling ``UpdatePowerState`` too early. Moving it into the Callback the ui updates properly now.

No offense to anyone but bl**dy hell, this is one complicated plugin :fearful:

**Pull request merged**
