### PR TITLE
Fix icons

### PR DESCRIPTION
**Pull request by infirit**
Todo

- ~~Add something similar for IconPixmap~~
- Handle errors in loading the icon
- Update scalefactor
- ~~Wayland has no primary monitor, find another way to get scale factor.~~
- Fix MATE (sort of fixed, it's slightly transparent :eyes: )
- ~~fix typing~~

### CODE REVIEW

**Comment by cschramm** [comment]
Quickly tested with mate-panel:

* Does not fix the tray icon itself.
* Fixes custom icons for menu items, especially `blueman-send-symbolic`.
* Sets correct scale factor 1 but...
* ...shows icons twice the size as usual. Changing the size to 16 brings back the expected icon sizes.

**Comment by infirit** [comment]
> That is really strange, Xfce and Plasma are fine. I'll add it to the list.

It wasn't me this time :rofl: . It's also broken for me with 2.3.5 from arch repos. It seems like IconName is not picked up by MATE panel.

**Comment by cschramm** [comment]
Yes, I can confirm that. The icons only become available in the default icon theme after installing the package a second time. :see_no_evil:

**Comment by cschramm** [comment]
> > Quickly tested with mate-panel:
> > ```
> > * Does not fix the tray icon itself.
> > ```
> 
> That is really strange, Xfce and Plasma are fine. I'll add it to the list.

The problem with the tray icon itself is that our `StatusNotifierItemService` provides the `IconName` (`blueman-tray`, `blueman-active`, or `blueman-disabled`) and obviously the server cannot find that icon if it is not installed. This PR currently fixes the same problem with icon names (now icon-data so that the server does not have to find anything) in `MenuService` but not in `StatusNotifierItemService`.

I'm surprised it works in Xfce and Plasma. Are they able to find the icons from the GResource? :thinking:

**Comment by infirit** [comment]
> I'm surprised it works in Xfce and Plasma. Are they able to find the icons from the GResource? thinking

I doubt it. It somehow find a regular bluetoot/blueman icon. When I implement IconPixmap it should be fixed.

**Comment by infirit** [comment]
> When I implement IconPixmap it should be fixed.

Done that and the right icons are showing. It's not quite right yet but getting there, slowly..

**Comment by cschramm** [comment]
Not sure if you're seeing the same but some icons are somehow very transparent for me now.

Bildschirmfoto zu 2022-12-08 20-59-34

**Comment by infirit** [comment]
Yes. It doesn't happen with "our" icons and also not with adwaita. I'm going to give up on this for now and revert the whole thing.

**Pull request closed without merging**
