### PR TITLE
Simple sendto plugin for caja, nemo and nautilus

### PR DESCRIPTION
**Pull request by infirit**
Needs a little cleanup still but is functional. Comments, criticism etc welcome.

Instead of doing a very complicated extension to use the DeviceSelectorWidget just call ``blueman-sendto`` with the appropriate argument for the files. ref #220

### CODE REVIEW

**Comment by infirit** [comment]
Screenie

**Comment by cschramm** [comment]
I cannot confirm that it works as caja is currently segfaulting for me, but I can confirm the same snippet works for nemo (#595) if I just replace `Caja` with `Nemo`. :smiley: It also works for nautilus by using `Nautilus` but the icon is missing and `get_background_items` needs to be implemented and return a (empty) list to avoid a warning.

**Comment by infirit** [comment]
>I cannot confirm that it works as caja is currently segfaulting for me

Ouch, I'll try it in a VM, Debian testing?

The python bindings have not changed between the various forks and the original. The extension should work in all of them with little modification. However, Gnome (thus nautilus) decided in their infinite wisdom that menu's shouldn't have icons, that is why its missing.

I'll add a stub for ``get_background_items`` so that if people want to use it under Nautilus their logs are not spammed.

**Comment by cschramm** [comment]
Segfault resolved. My GTK+ was too recent / caja was too old. caja 1.16 was added to unstable just yesterday and works fine. :smiley: 

Regarding Gnome's infinite wisdom: Right, other items do not have icons as well, just the main entry ("Open with [default app]") does.

So it looks like we can just put in `Caja`, `Nemo`, and `Nautilus` with some autotools voodoo and cover all three with just one script.

**Comment by infirit** [comment]
>with some autotools voodoo and cover all three with just one script.

voodoo added :smiling_imp:

Gentoo does not come with [nemo-python](https://github.com/linuxmint/nemo-extensions/blob/master/nemo-python/nemo-python.pc.in#L7) but checking the source it is identical to caja and nautilus.

I still want to use Gio to launch ``blueman-sendto`` instead of ``os.popen``

**Comment by infirit** [comment]
Now using Gio to start ``blueman-sendto``. We could at some point use the our ```Manager``` class to add a submenu with the paired devices. But for now this should do I think :smile:.

**Comment by cschramm** [comment]
Awesome. Installs and works fine for me for all three. There's a typo in the help strings, but who cares. :laughing:

**Comment by infirit** [comment]
>There's a typo in the help strings

Oops, I see them in configure.ac. Fixed those. unless something comes up I'll merge this in a couple of days.

**Pull request merged**
