### PR TITLE
Functions.py, StandardItems.py: hide or show window on clicking the status icon.

### PR DESCRIPTION
**Pull request by yars068**
That is another realization of 4bfa4399db76b04ad78bca74bdf20d3e332c61f6, nothing three-if's :)

### CODE REVIEW

**Comment by infirit** [comment]
d8bf0b89292a7573cf4f00c93891f1655f14029b

**Comment by cschramm** [comment]
This is buggy! If the lock file does not exist, the get_pid function raises an unhandled IOError.

**Comment by infirit** [comment]
Not really a problem with this change more with 735a7544e64bb1a3bb0929e4cb2eb1f2f2f41ee0.

fixed with 3ce97e90c9f1dbe53cb3363245343fdccf216592.

**Comment by cschramm** [comment]
Right, I didn't notice the except clause was more generic before.

**Pull request closed without merging**
