### PR TITLE
Put recent connections in toplevel applet menu

### LINKED ISSUE #1558: UI improvements suggestions
Here are a few UI suggestions which will greatly improve the usability of the app.

1) Add a connect button next to each item in devices so the user does not need to right click and open a context menu. This reduces 1 click and is simpler

2) Replace "search" button with "refresh" or "Search/Refresh". Its not clear that search is searching for devices and not searching within the already existing devices. 

3) Show the device list in the drop down menu on the toolbar. Why make the users open another window when they want to connect? Its really annoying

4) Don't show "Bluetooth devices ready" popup. Only show an error if they are not ready.

Thanks

### PR DESCRIPTION
**Pull request by cschramm**
Other applets like NetworkManager's do not try to keep menu small, so why should blueman...

Closes #1558

This was lying around for a while now. I'm not happy with the presentation yet and don't have any better idea for it but in general this should be good.

### CODE REVIEW

**Comment by infirit** [comment]
I tried it and outside of duplicated entires for devices and it being mixed in with the recent connections I worry about the exit menu running off the screen. How are we going to make sure when someone has 24 set as the max recent connections exit is still accessible?

I was thinking of adding an expander when we reach, let's say 6 recent, and hide older ones. This however is going to complicate the current design so yeah.. not sure what's worse.

**Comment by infirit** [comment]
I'll test with 24 and see how the menu behaves.

**Comment by cschramm** [comment]
When I considered #1558 I thought about an adapting expander as well, but came to the conclusion that just adding everything to the top level should be fine. Some arguments for "don't worry about large menus":
* The default maximum for recent connections is 6.
* If I remember correctly, back when I wrote the code I looked at nm-applet and found that they have no limit for their menu at all (or least something huge like 30 or something), so they do not seem to worry either.
* At least GTK-based menu implementations typically show a concept of scrolling, so if all goes wrong, all we get is a scrolling but still usable menu.

I can imagine that it might get rather nasty on low resolutions, though, but I guess at least as people do not increase the default maximum, they should be fine.

Duplicate devices? 🤔 Ah, you mean standard connect vs recent connection items?

**Comment by cschramm** [comment]
Just checked a very low resolution and indeed multiple status icon menus - including our current one - started scrolling (mate-panel). Also, it looks like I did *not* remember correctly regarding nm-applet. It shows 5 networks and puts more into a submenu.

In any case, if we talk about adding 5 items on toplevel, plus a submenu item, so that it's up to 6 vs. just adding all items on toplevel that's the same number in 99.9 % of all cases as 6 is exactly our default maximum of recent connections and I don't think it's worth addressing the very special case of an increased maximum *and* a low resolution just to avoid scrolling in the menu if we're lucky.

**Comment by infirit** [comment]
Thanks for checking.

This is what I am seeing. The duplicate Devices (Apparaten) was because I used the tray from master instead of this PR. But it still shows up in the middle of all the recently connected devices.
afbeelding

**Comment by cschramm** [comment]
Ouch, yeah, stupid me. The position indexes start to overlap at some point. :facepalm:

**Comment by infirit** [comment]
it's still duplicating entries with the latest changes.
image

Other than that it looks ok to me.

**Comment by cschramm** [comment]
I cannot replicate any duplication. :thinking:

> The duplicate Devices (Apparaten) was because I used the tray from master instead of this PR.

again?

**Comment by infirit** [comment]
> again?

Eeuh, wait, i get deja Vu, i may have done "it" again 😮‍💨

**Comment by infirit** [comment]
Can you rebase this one last time :-). I'll make sure to test this weekend.

**Review by infirit — APPROVED** [review]
Made sure to properly install and restart :grin: . All looks good now.

**Pull request merged**
