### PR TITLE
ManagerDeviceList: Hide devices with no name

### PR DESCRIPTION
**Pull request by infirit**
I don't like the menu entry name but at 1 in the morning I am out of ideas :sleepy:. If you have a suggestion feel free to comment.

### CODE REVIEW

**Comment by cschramm** [comment]
I'm not really sure if this is a good idea. The hypothesis is that once you set devices into pairing mode, they do provide a name? I'll test some devices to see if that holds.

If that's correct, don't we have to add devices on property changes (i.e. when a name appears) as well then? Currently we only add them when they show up initially.

Regarding the terms: unnamed, unknown, anonymous? A no name device is typically Chinese with no name on it. :wink:

**Comment by infirit** [comment]
> The hypothesis is that once you set devices into pairing mode, they do provide a name?

Not really but if they do they will show up when searching. Android literally hides these when searching and you have to go into developer options to change it. I think windows does the same as I never see them there as well. I don't own one of these devices but have plenty showing up from my neighbours. If you do have one It would be nice if you can test this :smile: .

> If that's correct, don't we have to add devices on property changes (i.e. when a name appears) as well then? Currently we only add them when they show up initially.

I can move this into a filter function on the liststore but this is a pita to do.

> Regarding the terms: unnamed, unknown, anonymous?

Unnamed sound much better. I'll reverse the logic and make the menu entry "Show unnamed". Maybe add a little tooltip with explanation.

**Comment by cschramm** [comment]
I tried to the hypothesis a little bit but did not find good examples. I guess it's valid, though. We can try.

**Comment by cschramm** [comment]
After playing with Bluetooth a little bit in the last time I'm rather confident that this *is* a good idea now. :smile:

**Comment by infirit** [comment]
Cool. I'll fix them conflicts later this week.

**Review by cschramm — DISMISSED** [review]

**Comment by cschramm** [comment]
Definitely deserves a changelog entry.

**Comment by infirit** [comment]
Doh!! 😫. I'll do it tonight.

**Review by cschramm — APPROVED** [review]

**Comment by infirit** [comment]
Rebased and updated changelog.

**Pull request merged**
