### PR TITLE
Rename nautilus-sendto to caja-sendto

### PR DESCRIPTION
**Pull request by cschramm**
Nautilus 3 does not support sendto plugins anymore while caja does.

Also use the external header instead of shipping it.

References #220 

Note that the dependency on the external header is currently not reflected by configure.ac; not sure if it needs to.

### CODE REVIEW

**Comment by infirit** [comment]
I pushed a commit makes the build correct. But there is, afaik, an unsolvable problem, see below the traceback.

My thought was instead of using python in the plugin just invoke ```blueman-sendto``` with ```GAppInfo```.

````python
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/gui/NstBluetooth.py", line 1, in <module>
    from gi.repository import Gtk, GObject, Pango
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 39, in <module>
    raise ImportError(_static_binding_error)
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
````

**Comment by cschramm** [comment]
The reason for the Python code seems to be to use the `DeviceSelectorWidget` within sendto.

I'm seeing an issue when using the plugin in caja:

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/blueman/gui/NstBluetooth.py", line 1, in <module>
    from gi.repository import Gtk, GObject, Pango
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 67, in load_module
    dynamic_module._load()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 296, in _load
    self._overrides_module = importlib.import_module('gi.overrides.' + self._namespace)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1554, in <module>
    initialized, argv = Gtk.init_check(sys.argv)
AttributeError: 'module' object has no attribute 'argv'
````

Cannot make any sense of that... :cry: 

Concerning the gobject issue: Can't we just remove the call to `pygobject_init`? I don't think it's necessary as we're not really using the API, just the PyGObject type.

**Comment by cschramm** [comment]
The reason for the Python code seems to be to use the `DeviceSelectorWidget` within sendto.

I'm seeing an issue when using the plugin in caja:

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/blueman/gui/NstBluetooth.py", line 1, in <module>
    from gi.repository import Gtk, GObject, Pango
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 67, in load_module
    dynamic_module._load()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 296, in _load
    self._overrides_module = importlib.import_module('gi.overrides.' + self._namespace)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1554, in <module>
    initialized, argv = Gtk.init_check(sys.argv)
AttributeError: 'module' object has no attribute 'argv'
````

Cannot make any sense of that... :cry: 

Concerning the gobject issue: Can't we just remove the call to `pygobject_init`? I don't think it's necessary as we're not really using the API, just the PyGObject type.

**Comment by infirit** [comment]
I have no clue why you see that error :confused:, was this before or after my commit to fix the build?

I removed the lines for pygobject but it makes no difference.

Reading NstBluetooth, it basically only needs the devicelist to add the spawning of ```blueman-sendto```, but we already get this when we launch ```blueman-sendto``` without the device id anyway. So back to my original suggestion, why not use ```GappInfo``` to launch ```blueman-sendto``` directly :smile:

**Comment by infirit** [comment]
Or just query bluez directly for the devicelist? Perhaps expose this over dbus from blueman?

**Comment by cschramm** [comment]
> I have no clue why you see that error :confused:, was this before or after my commit to fix the build?

Both.

> I removed the lines for pygobject but it makes no difference.

I wonder where pygobject gets imported then. It definitely gets imported in pygobject_init, but if you removed that there must be another location...

> Reading NstBluetooth, it basically only needs the devicelist to add the spawning of blueman-sendto, but we already get this when we launch blueman-sendto without the device id anyway. So back to my original suggestion, why not use GappInfo to launch blueman-sendto directly :smile:

You're right. As blueman-sendto can provide the device list it's probably no big win to have it integrated into the caja-sendto GUI as well. So lets remove the python stuff from the plugin and keep the integration simple.

@stefano-k @infirit Do you want to have the plugin in blueman or caja-extensions? It looks like your preferred way is to ship the plugins with caja-extensions, so I'd just remove the old nautilus-sendto plugin on the blueman side then.

**Pull request closed without merging**
